### ISSUE TITLE
Pretendard Variable에 글자 '스'가 뜨지 않습니다

### ISSUE THREAD

**Issue by SuwonJ** [orioncactus/pretendard#109]
프리텐다드 가변 폰트에 글자 '스'가 빠져 있는것으로 보입니다

![image](https://user-images.githubusercontent.com/84270989/204476540-40d490c2-4af0-42eb-879e-f7ecd3c32566.png)

https://user-images.githubusercontent.com/84270989/204475779-b4b004c6-34b9-4ad8-a0d7-b4d7fc80f8a0.mp4

**Comment by orioncactus** [comment]
안녕하세요! 말씀하신 것처럼 TTF, 가변 웹폰트, 가변 다이나믹 서브셋으로 제공하는 Pretendard Variable에서 `스`가 누락되어 있는지 확인해보았는데요, 문제 없이 정상적으로 `스`가 표시되는 것으로 보입니다. 문제가 발생하는 환경이 정확히 어떻게 되는지 알 수 있을지요?

또한 Pretendard 소개 웹사이트에서 가장 먼저 보여지는 애니메이션 부분은 브라우저 최적화를 위해 `Pretendard 프리텐다드` 문자만 포함된 웹폰트로 표시하고 있습니다. 따라서 해당 섹션이 아닌, 다음 URL로 테스트해보시는 것을 추천드립니다.
- 가변 글꼴: https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/variable/pretendardvariable.css
- 가변 다이나믹 서브셋: https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/variable/pretendardvariable-dynamic-subset.css

**Comment by SuwonJ** [comment]
헉 죄송합니다 여러 환경에서 테스트해본다고 해봤는데 브라우저 최적화를 위해서 글자가 빠져 있었네요
설치된 폰트가 뭔가 문제였던거 같아요 재설치하니까 잘 표시되네요ㅠㅠ
