### ISSUE TITLE
Could I fork this font to make a Latin/Greek/Cyrillic-only version?

### ISSUE THREAD

**Issue by cssobral2013** [orioncactus/pretendard#11]
Note: Keeping your copyright notes, and adding my ones, of course.

**Comment by cssobral2013** [comment]
@orioncactus - Good, however I'm wishing to use this on desktop.

**Comment by orioncactus** [comment]
Then you can use the latest Pretendard release. It includes all of the Latin/Greek/Cyrillic character set. Can you tell me why you want the non-CJK subset version of Pretendard?

**Comment by cssobral2013** [comment]
@orioncactus - Because it looks better than original Inter (it looks closer
to San Francisco than original Inter).

Em qua., 14 de jul. de 2021 1:54 AM, Kil Hyung-jin ***@***.***>
escreveu:

**Comment by orioncactus** [comment]
Thank you for your compliment. I plan on consistently improving Pretendard to become a more general font.

I'll close this issue. And if you have another question, feel free to reopen this issue!
