### ISSUE TITLE
Variable font axis tag 중 wght만 적용가능한가요?

### ISSUE THREAD

**Issue by redvelvet-fan** [orioncactus/pretendard#111]
[https://learn.microsoft.com/en-us/typography/opentype/spec/dvaraxisreg](https://learn.microsoft.com/en-us/typography/opentype/spec/dvaraxisreg)
위 링크에 따르면 다른 태그들도 있는데
현제 Flutter 에서 사용해보려 하니까 wght(weight)를 제외한 나머지 태그들이
동작하지 않는거 같습니다.

**Comment by orioncactus** [comment]
안녕하세요!
Pretendard Variable에서는 `ital`, `opsz`, `slnt`, `wdth` 속성이 포함되어 있지 않습니다. 따라서 `wght` 속성만 지원합니다.

이들을 모두 지원하기에는 이러한 축들의 master를 생성해야 하는데요, 이는 용량이 배가 된다는 뜻이 되어 CJK 문자로 용량이 큰 Pretendard에서는 현실적으로 지원하는 데 어려움이 있습니다.

답변이 도움이 되었길 바랍니다. 이 Issue는 Close로 옮겨두겠습니다.
