### ISSUE TITLE
폰트 사이즈에 따른 뭉개짐?

### ISSUE THREAD

**Issue by jinnyum** [orioncactus/pretendard#113]
안녕하세요.. 제가 폰트를 사용하면서 궁금한게 생겨서요..

폰트 사이즈를 1em ( font-size:0.8em, font-weight:300 ) 에서 더 줄이면

글자에 부분 부분 뭉게짐? 블러? 같은 현상이 생기는데요..

이런건 왜 그런 걸까요..

![fontblur](https://user-images.githubusercontent.com/38673939/209621138-cbfb686a-05fe-4d6f-9804-568126ece3e8.png)

빨간 네모의
첫번째 소문자 의 ㅁ 의 윗줄
두번째 스트 에서 스 의 아래 ㅡ , ㅌ 의 아랫부분
세번째 다국어의 ㄱ 의 윗부분 

이런식으로 부분 부분 글씨가 선명했다 뭉게졌다 그러는데요..
원래 이렇게 될수 밖에 없는 구조 일까요..;;

**Comment by orioncactus** [comment]
안녕하세요! 말씀하신 현상은 저해상도 디스플레이에서 문자를 또렷하게 볼 수 있는 보정 기능인 Hinting—힌팅이 Pretendard에 적용되지 않았기 때문인데요, Pretendard에서 힌팅을 자동으로 적용하는 방법도 초기에 고려했으나, 자동 힌팅 기능이 적용된 본고딕과 비슷하게 일부 글자가 들쑥날쑥하게 보이는 문제가 있었고, 다음으로 수동 힌팅으로 적용하기에는 수많은 글자를 대응해야 하는 어려움으로 Pretendard에서는 힌팅 기능을 제외해 제공하고 있습니다.

따라서 말씀하신 13px 이하 환경에서 글자가 흐릿하게 보이는 문제를 해결하시려면, 글꼴 크기가 13px 이하인 상황에서 font-weight를 최소 400 이상으로 설정해 사용하시거나, 맑은 고딕이나 본고딕 등 힌팅이 적용된 글꼴을 사용하시는 것을 추천드립니다. 질문에 도움을 드리지 못해 죄송합니다.
