### ISSUE TITLE
[문의] macOS - iTerm2 터미널에서 폰트가 제대로 노출되지 않는 현상

### ISSUE THREAD

**Issue by roeniss** [orioncactus/pretendard#117]
안녕하세요, 이 이슈가 Pretendard 에만 국한된 이슈로 보이지는 않습니다만, 제가 검색을 잘 못하는 것인지 트러블 슈팅 문서를 찾지 못해 도움을 요청하게 되었습니다.

![CleanShot 2023-02-14 at 15 05 10@2x](https://user-images.githubusercontent.com/26613280/218653330-a9a92653-2317-4ae0-91ee-1779d08008d4.png)

위와 같이 Pretendard 또는 Pretendard Variable 폰트를 세팅하면 터미널 애플리케이션이 폰트를 제대로 보여주지 못하는 이슈가 있습니다.

이게 한국어가 들어간(?) 폰트가 문제가 되는 것인가 싶습니다. 왜냐면 Noto Sans Mono 는 잘 렌더링 되고, Noto Sans KR 은 위와 같이 비정상적으로 출력되기 때문입니다.

![CleanShot 2023-02-14 at 15 06 46@2x](https://user-images.githubusercontent.com/26613280/218653419-b487e9ff-7c51-447b-b2a1-340653927b13.png)

![CleanShot 2023-02-14 at 15 07 36@2x](https://user-images.githubusercontent.com/26613280/218653517-4f3123b2-bfde-4b20-9b0f-7dbabd71a5fc.png)

**Comment by roeniss** [comment]
+) 자세히 보니 한글 각각의 글자는 잘 보이고, 공백이나 영어 쪽에서 문제가 발생하는 듯 합니다

**Comment by black7375** [comment]
Noto sans Mono는 작동되고, Noto sans KR, 프리텐다드가 이상하게 나오는 점을 미루어봤을때 [고정폭](https://ko.m.wikipedia.org/wiki/%EA%B3%A0%EC%A0%95%ED%8F%AD_%EA%B8%80%EA%BC%B4) 여부의 영향일 수도 있을것 같네요

**Comment by roeniss** [comment]
@black7375 pretendard 는 고정폭 글꼴이라고 이해했는데 제가 잘못 이해한 것일까요?
<img width="1639" alt="CleanShot 2023-02-14 at 23 18 34@2x" src="https://user-images.githubusercontent.com/26613280/218764692-e25329d1-8d6c-40d8-ae80-73d4ff458867.png">

**Comment by kms0219kms** [comment]
#74 이슈랑 비슷해 보입니다.

**Comment by kms0219kms** [comment]
고정폭 개발 관련한 내용은 #44 에서 기존에 다뤘던 적이 있으니 참고해 주시면 좋을 거 같아요!

**Comment by roeniss** [comment]
맞네요. 감사합니다.

**Comment by orioncactus** [comment]
@kms0219kms님, 이전에 비슷한 주제로 나눈 이야기를 알려주셔서 감사드립니다! 

Pretendard는 고정폭으로 고려된 모양과 구조를 가지고 있지 않기 때문에, 고정폭 모양으로 자연스럽게 사용할 수 있는 Pretendard를 만들기에는 기존 Pretendard에 포함된 대부분의 글자 모양에 수정이 필요합니다. 따라서 작업량이 상당해 Pretendard에서는 고정폭 글꼴 지원을 고려하고 있지 않으며, 대신 더욱 많은 환경에서 더욱 쾌적한 읽기 환경을 가져갈 수 있는 방법들을 고민하고 힘쓰려고 합니다.

참고로 말씀하신 상황에서 쾌적하게 잘 쓸 수 있는 [Mono Plex KR](https://github.com/y-kim/monoplex)라는 글꼴이 있는데요, 이 글꼴을 대신 사용하시는 것을 추천드려봅니다 :) 이렇게 Pretendard에 관심을 가져주시고 아껴주셔서 감사드립니다!
