### ISSUE TITLE
How much English/Latin characters does this font have compared to Inter? | 이 글꼴은 Inter와 비교하여 얼마나 많은 영어/라틴 문자가 있습니까?

### ISSUE THREAD

**Issue by Derpitron** [orioncactus/pretendard#120]
I want to use this font instead of Inter in my UI design. But I want to know, how many Latin/English characters, or other symbols and scientific characters are in this font compared to Inter? Have any characters been removed from Inter to Pretendard?

내 UI 디자인에서 Inter 대신 이 글꼴을 사용하고 싶습니다. 하지만 Inter에 비해 이 글꼴에 라틴어/영어 문자 또는 기타 기호 및 과학 문자가 몇 개인지 알고 싶습니다. Inter에서 Pretendard로 삭제된 캐릭터가 있습니까?

한국어나 일본어를 몰라서 구글 번역기를 사용하고 있습니다. 잘못된 문법에 대한 사과

**Comment by orioncactus** [comment]
Hello there! Pretendard has all of glyphs from Inter, so there's no problem with replacing Inter with Pretendard.

If you plan to use only Latin/Greek/Cyrillic with Pretendard, then you can use the Pretendard Std.

**Comment by orioncactus** [comment]
Glad to help you! :D

The only variant of Inter that I know of is [Interop](https://github.com/jhaemin/Interop), which combines Inter and [Source Han Sans KR(Noto Sans KR)](https://github.com/adobe-fonts/source-han-sans).
