### ISSUE TITLE
OS 별 브라우저에서 한글폰트의 길이가 다르게 잡히는 문제

### ISSUE THREAD

**Issue by takerlook** [orioncactus/pretendard#125]
<img width="265" alt="image" src="https://user-images.githubusercontent.com/47148451/226805199-69e1ec0c-ec92-41f8-8c7e-dc41617948e4.png">

ex) 안녕하세요 텍스트를 가진 버튼을 하나 만들었을 경우
MacOS Chrome에서는 width가 51.91px 로 잡히지만
<img width="264" alt="image" src="https://user-images.githubusercontent.com/47148451/226819952-1ea5a783-862c-4fbd-b96f-d190a64d02ac.png">

Window Chrome에서는 width가 60px로 잡히는 현상이 있습니다.

**Comment by quiple** [comment]
위 이미지의 폰트는 산돌고딕Neo1으로 보이고, 아래 이미지의 폰트는 맑은 고딕으로 보입니다.

해당 부분에 어떤 폰트가 로드되었는지 확인하세요. Firefox의 경우 이렇게 개발자 도구에서 확인할 수 있습니다:

<img width="242" alt="화면 캡처 2023-03-28 174146" src="https://user-images.githubusercontent.com/11014257/228180156-a13320da-b904-4185-8ebf-2423ec570ce2.png">

**Comment by takerlook** [comment]
@quiple Firefox에서 확인 결과 모두 동일한 폰트 사용하고 있는것으로 보이고 크롬에서만 해당 현상이 발생하고 있었습니다.
오늘 확인해보니 크롬 96버전에서 한글 폰트 렌더링하는 부분에 버그가 있었던거 같습니다.
크롬 업데이트  이후에는 정상적으로 표기되는것을 확인하였습니다.

**Comment by orioncactus** [comment]
@quiple 님, 이렇게 문제를 확인해주시고 알려주셔서 감사드립니다!

해결되어 다행입니다! 혹시나 다른 부분에서 문제가 생긴다면 언제든지 알려주세요!
