### ISSUE TITLE
안녕하세요 라틴어 지원 계획도 있으신지 궁금합니다

### ISSUE THREAD

**Issue by riflockle7** [orioncactus/pretendard#131]
안녕하세요 pretendard 폰트를 앱 개발하면서 감명 깊게 사용하고 있는 사람 중 한 명입니다. 
먼저 좋은 폰트를 제공해주심에 감사드립니다. 🙇‍♂️

혹시 라틴(latin) 어 지원 계획도 있으실 지 궁금합니다. 
유니코드 및 글자 예시: https://util.unicode.org/UnicodeJsps/character.jsp?a=1D05

현재 flutter 앱에서 라틴(latin) 어를 사용해봤는데, Android 에서는 일부 글자가 깨짐 현상이 있더라구요
[공식 문서](https://cactus.tistory.com/306) 내 `지원 언어` 에 라틴어 언급이 없기도 했어서 Issue 로 문의드려 보았습니다

감사합니다.

**Comment by orioncactus** [comment]
안녕하세요! Pretendard를 아껴주셔서 감사드립니다 ╰(*´︶`*)╯

라틴어는 로마자를 쓰는 언어이기 때문에, 로마자가 포함된 Pretendard는 라틴어를 지원하는 것이 맞습니다.

알려주신 문자 같은 경우에는 작은 대문자 모양으로, 일반적으로 쓰이는 문자는 아닌데요, 정확히 어떤 상황에서 저 문자가 쓰이는지 알 수 있을까요? 제가 파악하기로는 알려주신 작은 대문자는 Instagram에 프로필 소개로 꾸미는 경우가 아닌 다른 상황에서 보지는 못했던 듯합니다.
