### ISSUE TITLE
숫자 사이 "x"의 폰트가 다릅니다.

### ISSUE THREAD

**Issue by imki123** [orioncactus/pretendard#142]
- 이미지
![스크린샷 2023-06-20 오전 9 44 02](https://github.com/orioncactus/pretendard/assets/43270441/d4cd62ca-9ee9-4a74-a738-bb180ecfceb5)

- 4번째 문자인 x를 보면, 숫자 사이에서 x는 마치 곱하기 기호처럼 공중에 떠보입니다.
- 7번째 문자인 x를 보면, 영문 사이에서 x는 다른 알파벳처럼 정상적으로 보입니다.
- 모든 x를 일반적인 알파벳처럼 보이게 하고 싶은데 방법이 있을까요?

**Comment by devunt** [comment]
`font-feature-settings: "calt" 0;` 을 스타일시트에 추가해보시기 바랍니다.

**Comment by imki123** [comment]
> `font-feature-settings: "calt" 0;` 을 스타일시트에 추가해보시기 바랍니다.

답변 감사합니다! 잘 적용됐습니다 👍

**Comment by imki123** [comment]
이슈 해결되어 닫겠습니다.

**Comment by monsieur-mansa** [comment]
이걸 디폴트값으로 하면 안 될까요?
