### ISSUE TITLE
시스템 설치 글꼴 오작동 문제

### ISSUE THREAD

**Issue by conr2d** [orioncactus/pretendard#147]
### Description

기존에 Pretendard 1.3.6 버전 글꼴을 맥북 프로 16" (Intel) 시스템에 설치한 후 MS Office에서 사용하고 있었는데 최신 버전 (1.3.8)으로 업그레이드 한 후 제대로 작동하지 않는 문제가 발생했습니다.

Pretendard 글꼴을 사용했던 예전 문서를 열면 글꼴 크기가 더 크게 표시되어 영역을 뚫고 나가거나, 새로운 텍스트 박스를 생성하여 Pretendard 글꼴을 선택하면 적용되지 않습니다. (글꼴 선택 목록에 Pretendard 항목은 있는데 누르면 적용되어 있지 않고 변경 이전 글꼴이 유지됩니다)

1.3.6 버전으로 롤백했더니 잘되고, 1.3.7 버전도 적용해보니 문제 없네요. TTF로 사용중이었고 OTF로 테스트해봐도 결과가 동일했습니다. 전 1.3.7 버전을 사용하면 되긴 하는데 다른 분들도 문제 겪으실 수도 있을 것 같아 보고 드립니다.

### Environment

Version: Pretendard 1.3.8 (OTF, TTF)
System: macOS Ventura 13.4.1 (Intel)

**Comment by orioncactus** [comment]
안녕하세요! Pretendard를 쓰면서 생기는 문제와 함께 자세한 환경을 알려주셔서 감사드립니다.

v1.3.8에서는 레포지터리에서 제공하는 CSS 파일을 제외하면 모든 글꼴 파일이 v1.3.7과 동일하고 파일 변화가 없는데요, 혹시 다시 한번 확인해보실 수 있을까요? 지금까지 비슷하게 제보된 문제는 없어서, 자세한 조건을 확인해봐야 할 듯합니다.

**Comment by conr2d** [comment]
다시 1.3.8 버전 받아 테스트 해보니 잘 작동합니다. 특정 ppt 파일에서 문제가 있었는가 싶기도 하네요. 번거롭게 하여 죄송합니다. 덕분에 좋은 글꼴 잘 쓰고 있습니다. 감사합니다.
