### ISSUE TITLE
Safari 와 Chrome 에서 텍스트 렌더링 위치의 이슈.

### ISSUE THREAD

**Issue by synthresin** [orioncactus/pretendard#149]
안녕하세요. Pretendard 항상 감사하게 사용하고 있습니다.

다름이 아니라, 최근에 같은 요소에서 사용할때 시각적으로 서체가 표시되는 위치가 다른것을 발견하여서, 혹시 이것이 서체 레벨에서 대응되야만 해결될수 있는 문제인지 확인하고 싶어 문의드립니다.

이하의 사례는 10px fontSize에, 18px lineHeight를 적용하여 UI를 구성할때의 맥 사파리와 맥 크롬의 렌더 차이를 보여주고 있습니다.
(사파리가 1정도 내려가 보입니다.)

실상 CSS 레벨에서는 이 이상 크게 손댈일은 없다고 생각이 되고, 보통 서체를 임베딩하여 사용할때 lineHeight 지정을 잘 해두면, 브라우저에 따라 서체 렌더링 세로 위치가 달랐던적은 없었던것 같아 제보드립니다.

항상 감사합니다.

![CleanShot 2023-07-05 at 18 28 32@2x](https://github.com/orioncactus/pretendard/assets/1055213/a60f4f91-d554-4dfa-b84d-9d50cad3d2cd)

**Comment by orioncactus** [comment]
안녕하세요! Pretendard를 아껴주셔서 감사드립니다 ☺️

Safari와 Chrome은 픽셀 렌더링에서 소수점 처리 방식이 서로 다릅니다. Chrome은 렌더링되는 픽셀에서 소수점으로 표시되는 값을 반올림해 계산하고, Safari는 소수점을 내림으로 계산합니다. 따라서 line-height를 배수로 쓸 때 이런 상황을 맞춰 고려하지 않으면 보여주신 것처럼 각 브라우저에서 다르게 나타납니다.

배수로 쓰면서도 두 브라우저에서 높이를 맞추고 싶다면, font-size와 line-height를 곱했을 때 나오는 값을 내림으로 했을 때 잘리지 않게 line-height 배수 값을 맞추거나, 배수가 아닌 절대값으로 쓰는 방법이 있습니다.

**Comment by synthresin** [comment]
네. 고정 px 로 넣을떄도 이런문제가 생기는데, 서체에서 정의된 메트릭에 대하여 렌더링 엔진에서 처리하는 라운딩 방식이 각자 다르다라고 이해하면 되겠지요?
저는 혹시나 서체 메트릭쪽을 조절하면 어떻게 해결해볼수 있지 않을까 싶었습니다. (제가 서체 메트릭 프로퍼티에 대해서는 문외한이라..)

어쨋든 감사합니다! 그럼 일단 크롬 중심으로 맞추는 수 밖에 없겠네요..

**Comment by orioncactus** [comment]
맞습니다. 브라우저에서 글꼴에 정의된 메트릭 값을 처리할 때 어림 방식이 각각 달라 생기는 문제로 예상합니다.

이를 맞추기 위해 메트릭 값을 수정한다 하더라도 기준 메트릭 값을 모든 글꼴 크기에서 알맞은 수로 어림할 수 없기 때문에 해당 이슈를 해결할 수 없을 것으로 보입니다. 궁금하셨던 부분에 조금이나마 도움이 되었으면 좋겠습니다!
