### ISSUE TITLE
사용중인 회사 목록 리스팅

### ISSUE THREAD

**Issue by devxoul** [orioncactus/pretendard#15]
오픈소스 프로젝트의 신뢰도를 높이고 참여감을 높이기 위해 사용하고 있는 회사를 리스팅하는 경우가 많습니다. 사용중인 회사의 멤버들이 비교적 가볍게 로고를 올리는 정도로 Pretendard에 기여할 수 있는 기회를 만들어 주기도 하고요. Pretendard도 사용중인 회사 목록을 리스팅해보면 어떨까요?

아래는 예시입니다.

* [ReactorKit](https://github.com/ReactorKit/ReactorKit)
    <img width="886" alt="Screen Shot 2021-07-20 at 1 02 13 PM" src="https://user-images.githubusercontent.com/931655/126260129-78aa1c52-062a-416f-b684-ac7c2f16f826.png">
* [ReactiveX](http://reactivex.io/)
    <img width="911" alt="Screen Shot 2021-07-20 at 1 01 39 PM" src="https://user-images.githubusercontent.com/931655/126260122-1de4281f-2d5b-4b65-acc7-9fa909130e0e.png">
* [React Native](https://reactnative.dev/)
    <img width="1047" alt="Screen Shot 2021-07-20 at 1 03 29 PM" src="https://user-images.githubusercontent.com/931655/126260216-71df431f-0784-440d-9020-99a49a4e2dba.png">

**Comment by orioncactus** [comment]
건의해주시고 직접 Pull Request까지 올려주셔서 너무 감사드립니다! 올려주신 Pull Request를 적용하고 더 많은 사람들과 함께 성장하는 Pretendard 프로젝트가 될 수 있도록 꾸준히 신경쓰겠습니다. 🚀
