### ISSUE TITLE
Pretendard GOV 웹폰트 CDN 관련

### ISSUE THREAD

**Issue by kms0219kms** [orioncactus/pretendard#151]
Pretendard GOV가 release된지 좀 되었기에,
unpkg에 sync를 확인했고 cdnjs에 issue를 남겨두었습니다.

cdnjs에 남긴 issue가 close되면 GOV쪽 문서에도 unpkg와 cdnjs 링크를 남기면 좋을 것 같습니다.

(정부에서도 직접 호스팅하거나 cdnjs에서 임포트하는게 다반사라 이 작업을 진행했습니다.)

**Comment by kms0219kms** [comment]
[cdnjs/packages#1590](https://github.com/cdnjs/packages/issues/1590)

**Comment by kms0219kms** [comment]
![image](https://github.com/orioncactus/pretendard/assets/67222970/ffd4a902-4345-480f-bfbf-9d2afda2b646)

**Comment by orioncactus** [comment]
@kms0219kms 님 안녕하세요!

cdnjs는 현재 [Pull Request](https://github.com/cdnjs/packages/pull/1592)가 올려진 단계네요! 추가가 완료되면 unpkg와 함께 문서를 업데이트해두려고 합니다.

이렇게 소중한 시간을 내어 cdnjs에서도 Pretendard GOV를 쓸 수 있게 cdnjs에 이슈를 올려주시고 도와주셔서 진심으로 감사드립니다! 🥺✨

**Comment by kms0219kms** [comment]
추가 완료된 것으로 보입니다!

**Comment by orioncactus** [comment]
방금 업데이트되었군요! 저도 확인해보니 아직은 서버에 올려지지 않은 듯해서, 올려지는대로 다시 확인해보겠습니다.

- 확인 URL:
    - https://cdnjs.cloudflare.com/ajax/libs/pretendard-gov/1.3.8/static/pretendard-gov.css
    - https://cdnjs.cloudflare.com/ajax/libs/pretendard-gov/1.3.8/variable/pretendardvariable-gov-dynamic-subset.css

**Comment by orioncactus** [comment]
아직 확인이 안 되는데, 버전 태그가 새로 붙어야 반영되는 게 아닐까 싶네요 🤔 이후에 새 버전을 달 때 확인해보겠습니다.

**Comment by kms0219kms** [comment]
그러진 않는데, cdnjs쪽에 npm sync 주기가 존재하나 봅니다. 조금 더 기다려 보는거로 하겠습니다.

**Comment by kms0219kms** [comment]
@orioncactus sync 확인되었습니다. ^^

**Comment by kms0219kms** [comment]
![image](https://github.com/orioncactus/pretendard/assets/67222970/ea57ecc2-f639-457d-bdb7-39a408cb6df0)

**Comment by kms0219kms** [comment]
무슨 일인지 variable은 누락되어 있네요. Issue 열어서 다시 확인해 보겠습니다.

**Comment by kms0219kms** [comment]
I am not quite sure what is happening here -- the logs would suggest it was never published to the CDN properly: https://github.com/cdnjs/logs/tree/prod/packages/p/pretendard-gov/1.3.8



I have flagged this internally for investigation.

**Comment by kms0219kms** [comment]
정상 작동이 확인되었습니다. 리드미 업데이트 되면 될 듯 합니다. @orioncactus

**Comment by orioncactus** [comment]
@kms0219kms 님, 이제야 확인했습니다! 다음주 주말 안으로 cdnjs로도 쓸 수 있게 Readme를 업데이트하겠습니다. 이렇게 알려주시고 CDN 다중화를 위해 힘써주셔서 감사드립니다! 🔥
