### ISSUE TITLE
원문자 크기 다름

### ISSUE THREAD

**Issue by jglee96** [orioncactus/pretendard#152]
웹 환경에서 원문자 (①②③④⑤⑥⑦⑧⑨⑩⑪⑫⑬⑭⑮) 사용시,
①②③④⑤⑥⑦⑧⑨의 크기가 설정된 폰트 크기보다 커보입니다.

눈누에서 확인한 이미지 첨부합니다.
![image](https://github.com/orioncactus/pretendard/assets/22130454/d64c6726-a888-4093-925c-5ef687805429)

**Comment by orioncactus** [comment]
안녕하세요! 현재 GitHub에서 제공하고 있는 최신 버전 Pretendard에서는 아래와 같이 표시되니, 편히 사용하시면 좋겠습니다 (▰˘◡˘▰) 

<img width="863" alt="image" src="https://github.com/orioncactus/pretendard/assets/7247848/3deb0f82-7f2e-4100-bdb6-af2860606dcc">

또한 눈누에서 제공 중인 Pretendard 버전이 이전 버전으로 지금과는 다른 심벌 문자가 표시되고 있음을 알려주셔서 감사드립니다 :) 제가 시간이 될 때 눈누에 메일로 글꼴 파일 업데이트가 가능한지 문의를 드려보겠습니다.

**Comment by jglee96** [comment]
> 안녕하세요! 현재 GitHub에서 제공하고 있는 최신 버전 Pretendard에서는 아래와 같이 표시되니, 편히 사용하시면 좋겠습니다 (▰˘◡˘▰)
> 
> <img alt="image" width="863" src="https://user-images.githubusercontent.com/7247848/254281611-3deb0f82-7f2e-4100-bdb6-af2860606dcc.png">
> 또한 눈누에서 제공 중인 Pretendard 버전이 이전 버전으로 지금과는 다른 심벌 문자가 표시되고 있음을 알려주셔서 감사드립니다 :) 제가 시간이 될 때 눈누에 메일로 글꼴 파일 업데이트가 가능한지 문의를 드려보겠습니다.

감사합니다!
