### ISSUE TITLE
[문의] window에서 폰트가 옅게 보이는 현상

### ISSUE THREAD

**Issue by DevSoon** [orioncactus/pretendard#156]
제공하시는 [CDN](https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.8/dist/web/variable/pretendardvariable-dynamic-subset.css)으로 폰트를 적용했는데 윈도우와 맥북 크롬에서 폰트의 두께가 다르게 보이는 것 같습니다. 

폰트 크기를 12~13px로 하고 weight를 400으로 했을 때 윈도우에서 폰트가 더 옅게보이는 것 같아요. 한글로 입력했을 때 더 차이가 크게 나타나는데 혹시 확인 부탁드려도 될까요?

**Comment by DevSoon** [comment]
안녕하세요. 일정기간 추가로 관련된 내용이 없는 것 같아 해당 이슈를 닫을려고 합니다. 만약 이와 관련하여 추가적인 의견이나 질문이 있으시면 언제든지 말씀 부탁드립니다. 감사합니다

**Comment by orioncactus** [comment]
안녕하세요! 답장이 매우 늦어 죄송합니다 😅

말씀하신 현상은 macOS에서 저해상도 디스플레이를 위한 글꼴 렌더링이 자체적으로 적용되어 macOS에서 원래 모습보다 더욱 굵게 표시되는 것인데요, Figma나 iOS, Windows에서 보여지는 모습과 비슷하게 맞추시려면 css 전역에 아래와 같은 속성을 추가하시면 됩니다: `-webkit-font-smoothing: antialiased;`

혹시나 적용하시는 데 어려움이 있거나 도움이 필요하시면 언제든지 알려주세요!

**Comment by hyjoong** [comment]
저는 Pretendard Variable 폰트를 로컬에서 다운로드하여 사용하고 있는데, windows에서는 폰트의 굵기가 정상적으로 적용되지만, macOS에서는 설정된 굵기보다 약 100 정도 더 굵게 표시되는 문제가 있어서
`-webkit-font-smoothing: antialiased` 속성을 적용해서 문제를 해결했는데 같은 문제였을까요??

**Comment by hyjoong** [comment]
저는 Pretendard Variable 폰트를 로컬에서 다운로드하여 사용하고 있는데, windows에서는 폰트의 굵기가 정상적으로 적용되지만, macOS에서는 설정된 굵기보다 약 100 정도 더 굵게 표시되는 문제가 있었습니다. 
`-webkit-font-smoothing: antialiased` 속성을 적용해서 문제를 해결했는데, 같은 이슈였을까요??

다운받았던 Pretendard Variable의 버전은 잘 모르겠습니다.

**Comment by orioncactus** [comment]
@hyjoong 님 안녕하세요! 맞습니다. 위에 적은 것과 같이 macOS에서 유지하고 있는 폰트 안티앨리어싱 처리 방식으로 다른 플랫폼이나 그래픽 애플리케이션과 비교해 폰트가 더욱 굵어보일 수 있습니다. 이는 Pretendard 및 Pretendard Variable 모두 동일합니다.
