### ISSUE TITLE
웹 브라우저 문맥 대체 기능(font-feature-settings: 'calt')과 한글 혼용 문제

### ISSUE THREAD

**Issue by leones00** [orioncactus/pretendard#159]
![Screenshot 2023-09-14 at 18-11-03 Pretendard](https://github.com/orioncactus/pretendard/assets/37134260/d40c8fae-a796-4695-8471-1b503e7d58e2)
영어나 숫자가 아닌 문자와 혼용시 문맥 대체 기능이 제대로 적용되지 않는 듯합니다.
파이어폭스와 크롬, 엣지 브라우저 최신판에서 확인했습니다.
(위 스크린샷은 https://cactus.tistory.com/306 의 예시 부분을 개발자 모드에서 텍스트만 수정한 것입니다.)

**Comment by kms0219kms** [comment]
예시 부분의 경우 빠른 글자 렌더링을 위해 일부 글자만 포함되어 있습니다.
그래서 그런 문제가 발생하는건 아닐지 조심스럽게 추측해 봅니다. 여건이 되신다면, 다른 사이트에서 테스트를 해보시는 것도 좋습니다.

**Comment by black7375** [comment]
저도 파이어폭스와 엣지로 테스트를 해봤는데요,
혼용시에는 이슈가 있는것 같네요.

어쩌면 #108 와도 관련이 있을 수도..

https://codepen.io/black7375/pen/QWzgXwO

![image](https://github.com/orioncactus/pretendard/assets/25581533/9b5fc947-0cc1-4737-b9fc-18acc3ae992c)

**Comment by orioncactus** [comment]
안녕하세요! 저도 예전부터 알고 있는 문제이긴 합니다 😅

정확히는 OpenType 기능에서 `calt`—문맥 대체 부분에서 생기는 문제인데요, 제가 확인해본 것으로는 Adobe 애플리케이션을 제외한 웹 브라우저, OS 등 모든 환경에서 한글 unicode 영역에 있는 모든 문자에서 기능이 적용되지 않고 있습니다.

제가 보기에는 한글에서 문맥 대체를 쓰는 사례가 많이 없어 아직까지 조치가 안 된 것으로 예상하는데요, 우선 다음 배포 때 다른 feature 영역에 한글 문맥 대체를 넣는 식으로 맞춰 쓸 수 있도록 대응하려고 합니다. 또 시간이 될 때 관련해서 의견을 청취할 수 있는 분에게 메일로 알려드려보겠습니다.

따라서 당분간은 `font-feature-settings`에서 `ss05`—한국 현지화를 적용해 쓰시는 것을 추천드립니다. 이 이슈는 다음 배포 때 해결되는대로 맞춰 닫아두겠습니다 :)
