### ISSUE TITLE
subset정의 기준 추가 가능할까요?

### ISSUE THREAD

**Issue by GomUI** [orioncactus/pretendard#164]
제공된 폰트 중 일부 폰트에 대해서 subset로 된 파일들이 있는데 다른 파일과 비교했을 때 
폰트 내 글리프의 수가 다른데 아무래도 경량화를 위해 제작된 폰트로 보여집니다.

그렇다면 경량화를 하셨을 때 나름의 기준으로 가지고 subset을 정의를 했을 것으로 예상이 되는데 
그 기준에 대해서도 공개가 가능할지 문의 드립니다.

저 또한 경량화를 위해 subset를 정의를 했으나 프리텐다드에 정의된 한글 음절, 자모의 수가 제가 정의한 것과 
상이하여 프리텐다드는 어떠한 기준으로 정의를 했는지 궁금하여 문의를 남깁니다.

참고로 음절의 경우 완성형(2,350자)를 기준으로 정의를 했습니다.

**Comment by black7375** [comment]
각 패키지의 `subset_glyphs.txt`가 기본 서브셋입니다.
- https://github.com/orioncactus/pretendard/blob/main/packages/pretendard/subset_glyphs.txt

다이나믹 서브셋의 경우 배포되는 CSS파일의 `unicode-range`를 사용하여 생성됩니다.
- https://github.com/orioncactus/pretendard/blob/main/packages/pretendard/dist/web/static/pretendard-dynamic-subset.css

**Comment by GomUI** [comment]
@black7375 제공해주신 링크 감사합니다.
서브셋을 정의한 기준도 궁금합니다. 
앞서 문의 드렸듯이 저의 경우 한글 음절의 경우 완성형(2,350자)을 기준으로 정의했는데 전달주신 서브셋 파일에는 2,780자인데 어떠한 기준으로 2,780자가 됐는지가 궁금합니다.(추가로 한글 음절 및 자모 외의 문자는 나라표준인증([링크](https://standard.go.kr/KSCI/standardIntro/getStandardSearchView.do?ksNo=KSX1001))를 통해 정의 했습니다.)

또한, 다이나믹 서브셋(unicode-range)의 정의 기준도 궁금합니다.
단순하게 접근하여 다이나믹 서브셋을 정의하면 유니코드 순서대로 범주를 정의하고 그에 따라 폰트파일 생성 및 범주도 정의를 할 수 있을 것으로 판단이 됩니다.

**Comment by hiddenest** [comment]
@GomUI 서브셋의 경우 기존 2,350자로 인한 문제를 보완하기 위해 만들어진 Adobe-KR-9 기준을 따르고 있으며, 다이나믹 서브셋은 Google Fonts의 Noto Sans KR 생성 로직을 따르고 있습니다(구글에서 사용도 및 문자수의 우선도를 머신러닝 기반으로 분류, 효율화한 서브셋 모음).

관련 내용은 아래 이슈 링크를 걸어두었습니다 😃 
https://github.com/orioncactus/pretendard/issues/3
https://github.com/orioncactus/pretendard/issues/4

**Comment by GomUI** [comment]
@hiddenest 답변 및 링크 제공 감사합니다. 덕분에 경량화에 있어 좀 더 심도 깊은 기준을 마련할 수 있을 듯 합니다.
