### ISSUE TITLE
[문의] Error: No formulae found for ‘font-pretendard’.

### ISSUE THREAD

**Issue by yvnh** [orioncactus/pretendard#168]
안녕하셔요, 저는 Pretendard가 너무나 예뻐서
System-UI 폰트로 꼭 쓰고 싶었답니다.
하지만 저는 Windows11을 쓰고 있었고,
Github에는 $라는 코드만 적혀 있었지요.

컴알못인 저는 한참을 헤맨 끝에 겨우겨우
Windows11에서 Ubuntu를 설치하고,
그 다음 Homebrew를 깔았는데 하필
Error: No formulae found for ‘font-pretendard’.
![Error-No-formulae-found-for-font-pretendard](https://github.com/orioncactus/pretendard/assets/67695269/c436cb53-4559-42ae-bc9e-cb8c5d819faa)
라는 메시지가 뜨고 실행이 안 됩니다.

어떻게 하면 좋을지 모르겠네요.
제발 도와주세요. 꼭 쓰고 싶습니다😭

그리고 안드로이드에서도 Pretendard를
혹시 사용할 수 있는 방법이 있을까요?

너무너무 사용하고 싶은데,
zFont3 어플을 통해 사용하다가
얼마 전에 막혔거든요.

그래서 직접 어떻게 휴대폰으로 apk 파일을 만들어서
넣으면 되지 않을까 생각도 하고 있는데
이런 방법은 불가능할까요?

컴알못이라 이런저런 질문이 많은 점
정말 죄송합니다.

우선 저 에러메시지를 어떻게 해결할 수 있는지
제발 좀 알려주세요.
개발자 님께 도움을 구합니다.🙏

**Comment by orioncactus** [comment]
안녕하세요! Pretendard를 아껴주셔서 감사드리며, 이렇게 늦게 확인해서 죄송합니다.

사실 저도 방법을 잘 알지 못했는데, 해결 방법을 찾아주시고 [아티클](https://blog.naver.com/yvnh_/223286030526)로 공유해주셨군요! 많은 분들에게 도움이 되도록 이렇게 아티클까지 작성해주셔서 감사드립니다! 🥰

zFont3가 최근에 막혔을까요? 마음 같아서는 Android에서 지원하는 설치형 글꼴 패키지 방식인 FlipFont로 Pretendard를 설치할 수 있길 너무 바라나, 개인 대상으로 솔루션이 있지 않아 마땅한 방법이 없어 안타까운 심정이긴 합니다. 혹시나 관련해서 업데이트가 있다면 알려드리겠습니다. 이어서 이 이슈는 해결로 처리해두겠습니다! 💪
