### ISSUE TITLE
릴리즈 시 JSDelivr 캐시 초기화하는 방법을 수정

### ISSUE THREAD

**Issue by piquark6046** [orioncactus/pretendard#170]
현재 사용되고 있는 방법은 `/dist/web/static`와 `/dist/web/variable` 디텍터리를 초기화하라고 되어 있습니다만, 변경되지 않은 파일도 포함하여 초기화 요청을 하게 됩니다.

[List-KR/jsdelivr-purge](https://github.com/List-KR/jsdelivr-purge)를 사용하여 변경된 파일만 초기화 요청을 할 수 있도록 하는게 좋을 것 같습니다.

**Comment by orioncactus** [comment]
이렇게 이슈를 제보해주셔서 감사드립니다! :D PR에서 계속하겠습니다.
