### ISSUE TITLE
태국어도 지원해주시면 감사하겠습니다

### ISSUE THREAD

**Issue by chomg** [orioncactus/pretendard#174]
Pretendard에 태국어 폰트도 추가해주시면 감사하겠습니다. 많은 유니코드 폰트에서 태국어도 포함되어 있는데, Pretendard에는 태국어 폰트가 없어서 많이 아쉽습니다.

**Comment by orioncactus** [comment]
안녕하세요! 이렇게 Pretendard를 아껴주시고 Issue를 남겨주셔서 감사드립니다 :)

슬프게도 한국 서비스에서 태국어 사용 사례가 많지 않고, 글꼴 용량과 소스 코드 관리 포인트 증가 등 현재 Pretendard에서 추가적으로 살펴봐야 할 부분이 많기 때문에  아직까지 태국어 지원을 고려하고 있지 않습니다. 대신 Noto Sans Thai를 쓰시는 것을 추천드립니다.

지원을 고려하지 않고 있기 때문에 Issue는 닫힘으로 두겠습니다. 추가적으로 궁금한 부분이 있으시거나 도움이 필요하시면 언제든지 알려주세요!
