### ISSUE TITLE
macOS 의 Powerpoint 앱에서 이탤릭체가 너무 과하게 눕는거 같습니다.

### ISSUE THREAD

**Issue by parkleo121212** [orioncactus/pretendard#175]
<img width="1146" alt="image" src="https://github.com/orioncactus/pretendard/assets/72724576/915164c7-0bc9-405f-be49-8e60ff01c0df">

안녕하세요, 좋은 폰트 출시 때 부터 잘 사용하고 있습니다.

현재 masOS 14.3 DB 3, Macbook Pro 14인치 M1 Pro 모델에서 사용 중인데요,
위의 사진에서 위 프로그램은 한글, 아래 프로그램은 파워포인트 입니다.
한글은 한컴 독스 기준 최신 버전, 파워포인트는 Microsoft 365 기준 최신 버전입니다. 

폰트는 1.3.9 버전을 Github 에서 다운 받아서 otf 파일을 설치했는데, 위와 같이 파워포인트 앱에서만 폰트가 과하게 누워서 가독성이 떨어져 읽기 불편해지는 것 같습니다. 1.3.7 버전도 동일한 것 같아요. 폰트 weight 에 무관하게 항상 발생하는 거 같습니다. 
 
혹시 해결 방법에 대해서 알려주실 수 있을까요? 감사합니다!

**Comment by parkleo121212** [comment]
마이크로소프트 워드 앱에서도 동일합니다. 
또 추가로 확인해보았는데, 기본 텍스트 편집기 앱에서 Pretendard 폰트 선택 시 이탤릭체가 비활성화 됩니다. (Helvetica 같은 다른 폰트는 가능)
<img width="449" alt="image" src="https://github.com/orioncactus/pretendard/assets/72724576/c8c6776c-d6b3-4815-b0bc-c426e46b07d4">

이탤릭체를 강제로 렌더링하는 과정에서 문제가 생기는 걸 수도 있을 것 같습니다.

**Comment by orioncactus** [comment]
안녕하세요! Pretendard를 아껴주시고 Issue를 남겨주셔서 감사드리며, 늦게 답장드려 죄송합니다.

Pretendard에는 Italic체를 지원하지 않습니다. 따라서 보여주신 스크린샷과 같이 소프트웨어 단에서 강제로 Italic이 적용되어 매끄럽게 보이지 않을 수 있습니다.
Pretendard에서 Italic을 지원하려면 소스 코드 분기가 필요한데, 작업량이 상당해 아직까지 크게 고려하고 있지는 않습니다. 혹여나 해외 사용 사례가 많아지고 Italic 필요성이 대두될 때 한번 살펴보려고 합니다.

아직까지는 지원 예정이 없으므로 이 Issue는 닫은 상태로 두도록 하겠습니다. 추가적으로 궁금하신 부분이나 도움이 필요한 게 있다면 언제든지 알려주세요!
