### ISSUE TITLE
아랍어를 모두 지원하나요?

### ISSUE THREAD

**Issue by gusxodnjs** [orioncactus/pretendard#182]
안녕하세요. 신규 프로젝트에 pretendard 서체 적용을 검토하고 있습니다.

아랍어를 표기할 필요가 있는데 해당 폰트로 모두 지원 가능한지 문의드립니다.

**Comment by cog25** [comment]
![image](https://github.com/orioncactus/pretendard/assets/74242561/25755cfe-5499-4646-9f83-649875eefc01)
[블로그](https://cactus.tistory.com/306)에 따르면, 지원되는 글꼴에 아랍어는 존재하지 않습니다.

**Comment by orioncactus** [comment]
늦게 답장드려 죄송합니다!

슬프게도 Pretendard는 아랍 문자를 지원하지 않습니다. 대신 비슷한 오픈 소스 폰트인 [Noto Sans Arabic](https://fonts.google.com/noto/specimen/Noto+Sans+Arabic)을 쓰시는 것을 추천합니다.
