### ISSUE TITLE
LICENSE에 기반 폰트에 대한 copyright 및 reserved font name 누락

### ISSUE THREAD

**Issue by changwoo** [orioncactus/pretendard#191]
안녕하세요.

여러가지 다른 폰트를 기반으로 하고 있는데 당연하게도 LICENSE 파일에 그 기반 폰트에 대한 copyright 문구를 유지해야 합니다.

그리고 OFL의 reserved font name은 파생 작업에 대해서도 원본 reserved font name이 유지되어야 합니다.  기반 폰트의 copyright를 추가하면서 reserved font name 도 같이 추가해야 할 것으로 보입니다.

참고 문서: 
https://openfontlicense.org/how-to-modify-ofl-fonts/

**Comment by black7375** [comment]
제가 집에가서 작업해보겠습니다.

**Comment by orioncactus** [comment]
안녕하세요! 라이선스 파일에 누락된 정보를 찾아주시고 알려주셔서 감사드립니다. black7375님께서 #192를 올려주셨는데요, 굉장히 바쁜 관계로 이번주 주말 즈음에 확인해보겠습니다.

**Comment by orioncactus** [comment]
관련한 #192이 병합되어 완료 처리해두겠습니다 :) 이렇게 라이선스 표기 문제를 바로잡을 수 있게 알려주셔서 다시 한 번 감사드립니다.
