### ISSUE TITLE
jsDelivr URL이 동작하지 않음 [ERR : ERR_CERT_DATE_INVALID]

### ISSUE THREAD

**Issue by Leo-SingleDay** [orioncactus/pretendard#196]
![image](https://github.com/orioncactus/pretendard/assets/76560163/5a3b93dd-682d-4ae3-8d93-41d702cb97f5)

[Provisional headers are shown]

cdn으로 웹 폰트 다운로드시 해당 에러가 발생 하는것 같아요 !

혹시 수정사항이 있으신지 확인 한 번 부탁드립니다!

**Comment by orioncactus** [comment]
https://status.jsdelivr.com 에서는 정상 동작하는 것으로 안내하고 있으나, [jsDelivr Statistics](https://www.jsdelivr.com/statistics)는 표시되는 것이 없는 것을 보아 jsDelivr CDN이 멈춘 것 같습니다 ^_ㅠ 그동안 대응이 가능하다면 cdnjs 또는 UNPKG로 바꿔 쓰시는 것을 추천드립니다. 이어서 다음 액션을 확인해보겠습니다.

#### cdnjs
```
https://cdnjs.cloudflare.com/ajax/libs/pretendard/1.3.9/static/pretendard-dynamic-subset.min.css
```

#### UNPKG
```
https://unpkg.com/pretendard@1.3.9/dist/web/static/pretendard-dynamic-subset.css
```

**Comment by Leo-SingleDay** [comment]
빠른 답변 감사드립니다.

**Comment by black7375** [comment]
네, 지금 CDN이 터진 것 같습니다 ㅠㅠ
저희 회사에서도 jsDelivr관련하여 대응 중이네요.

**Comment by orioncactus** [comment]
https://github.com/jsdelivr/jsdelivr/issues/18565 SSL 갱신이 안 되어서 장애가 난 것 같군요 🥲

**Comment by orioncactus** [comment]
우선 jsDelivr 대응 상황을 보고 Pretendard에서 기본으로 안내하는 CDN을 유지할지, 바꿀지 고민해보려고 합니다.

**Comment by orioncactus** [comment]
그동안 임시로 해결하고자 하신다면 `cdn.jsdelivr.net` 대신 아래 도메인으로 바꾸시는 것을 추천드립니다:
- `fastly.jsdelivr.net`
- `gcore.jsdelivr.net`

**Comment by hubdncajh** [comment]
우선 일단 전달주신 경로로 붙혀서 운영중인 사이트 복구했습니다. 혹 기존 cdn이 복구되면 내용공유만 부탁드려도 될까요?

**Comment by orioncactus** [comment]
> 우선 일단 전달주신 경로로 붙혀서 운영중인 사이트 복구했습니다. 혹 기존 cdn이 복구되면 내용공유만 부탁드려도 될까요?

jsDelivr에서 복구가 확인되는대로 이 스레드에 바로 알려드리겠습니다 🔥

**Comment by composite** [comment]
@orioncactus jsdelivr 는 쓰지 않았으면 좋겠습니다. 지금 뿐 만 아니라 과거에도 같은 전례가 있는 사이트입니다.
readme 에도 대체 사이트를 제시했으면 좋겠습니다.

- https://cdnjs.cloudflare.com/ajax/libs/pretendard/1.3.9/static/pretendard.css
- https://unpkg.com/pretendard@1.3.9/dist/web/static/pretendard.css

복구를 기다리는 것보다 더 빠르게 대응할 수 있을 겁니다.

**Comment by orioncactus** [comment]
@hubdncajh 이제 cdn.jsdelivr.net가 복구되었네요 😂 참고하시면 좋겠습니다.

**Comment by orioncactus** [comment]
> @orioncactus jsdelivr 는 앞으로 일언반구도 없었으면 좋겠습니다. 지금 뿐 만 아니라 과거에도 같은 전례가 있는 사이트입니다. readme 에 `jsdelivr` 항목을 지우고 대체 사이트를 제시했으면 좋겠습니다. 아래는 예시입니다.
> 
> * https://cdnjs.cloudflare.com/ajax/libs/pretendard/1.3.9/static/pretendard.css
> * https://unpkg.com/pretendard@1.3.9/dist/web/static/pretendard.css
> 
> 복구를 기다리는 것보다 더 빠르게 대응할 수 있을 겁니다.

혹시 예전에 어떤 전례가 있었는지 자세히 알 수 있을까요? 말씀하신 내용을 참고해 맞춰 대응해보려고 합니다.

**Comment by composite** [comment]
> > @orioncactus jsdelivr 는 앞으로 일언반구도 없었으면 좋겠습니다. 지금 뿐 만 아니라 과거에도 같은 전례가 있는 사이트입니다. readme 에 `jsdelivr` 항목을 지우고 대체 사이트를 제시했으면 좋겠습니다. 아래는 예시입니다.
> > 
> > * https://cdnjs.cloudflare.com/ajax/libs/pretendard/1.3.9/static/pretendard.css
> > * https://unpkg.com/pretendard@1.3.9/dist/web/static/pretendard.css
> > 
> > 복구를 기다리는 것보다 더 빠르게 대응할 수 있을 겁니다.
> 
> 혹시 예전에 어떤 전례가 있었는지 자세히 알 수 있을까요? 말씀하신 내용을 참고해 맞춰 대응해보려고 합니다.

아 죄송합니다. cdnjs 하고 착각했네요. 정정해서, 여러 CDN 사이트를 소개하면 더 좋을 것 같습니다.

**Comment by joonseo05** [comment]
안녕하세요 이번 사태 같이 겪으며 리서치 하다가 보게 되었는데 한가지 더 첨언하고 싶은게 있어서요! 한달 안된거 같은데 unpkg.com쪽도 사이트 전체적인 문제는 아니었고, swiper 관련해서
https://unpkg.com/swiper/swiper-bundle.min.js를 https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js 로 도메인 리디렉션 작업을 하려고 했던거 같은데 한 3시간정도 오늘 사태와 똑같은 현상을 겪었던 적이 있었습니다. 개발력이 그리 길진 않지만 개인적으론 cdnjs.cloudflare쪽말고는 다 이런 사고를 겪어봐서 말을 덧붙여본니다!

**Comment by orioncactus** [comment]
> 안녕하세요 이번 사태 같이 겪으며 리서치 하다가 보게 되었는데 한가지 더 첨언하고 싶은게 있어서요! 한달 안된거 같은데 unpkg.com쪽도 사이트 전체적인 문제는 아니었고, swiper 관련해서
> 
> https://unpkg.com/swiper/swiper-bundle.min.js 를 https://unpkg.com/swiper@11.1.1/swiper-bundle.min.js 로 도메인 리디렉션 작업을 하려고 했던거 같은데 한 3시간정도 오늘 사태와 똑같은 현상을 겪었던 적이 있었습니다. 개발력이 그리 길진 않지만 개인적으론 cdnjs.cloudflare쪽말고는 다 이런 사고를 겪어봐서 말을 덧붙여봅니다!

이야기를 종합해보면 jsDelivr, cdnjs, UNPKG 모두 맹신해서는 안 되겠군요 🙄 완벽한 대안은 아직 없는 듯해 CDN 표시 우선 순위는 유지하겠습니다. 

+ jsDelivr에서 관련 트윗(https://x.com/jsdelivr/status/1785944623761756308?s=46&t=U3AN-WqCVErZfJnz6xxBtg)을 올리긴 했는데, 이번 일로 자체 호스팅으로 처리하는 사례들이 많아질 듯합니다 😅

> Today, for an unknown reason, our SSL certificate with Cloudflare, which is fully automated and managed by them, was replaced with an expired one.
> This was completely unexpected and something we weren't prepared for, and caused unavailability of our service in some regions.
> 
> As a temporary solution, we've redirected all traffic to Fastly until we better understand what happened and can safely bring Cloudflare back.
> We apologize for the troubles this outage caused and will make sure it doesn't happen again.
