### ISSUE TITLE
Google Fonts 추가 요청

### ISSUE THREAD

**Issue by soulee-dev** [orioncactus/pretendard#200]
안녕하세요! Pretendard를 많이 사용하는 한 유저입니다.
Pretendard를 개발해주셔서 정말 감사합니다.

폰트 사용중에 하나 불편한 점을 발견해서 Issue를 등록했습니다.

**바로 Google Fonts에 Pretendard가 추가 되어있지 않다는 것 입니다.**
Google Fonts에 추가된다면, NextJS와 같은 프레임워크에서도 훨씬 편하게 적용할수 있겠다는 생각이듭니다!

혹여나 도움이 필요하시다면, 번거로운 작업은 저도 같이 도와드리고 싶습니다.

감사합니다!

참고자료:
[Google Fonts CONTRIBUTING.md](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)

**Comment by bashruv** [comment]
지나가던 유저입니다.
동일 내용의 이슈(#7)가 오픈상태로 아직 존재합니다.
해당 이슈에서 코멘트 내용을 전달하는 것이 어떨까요?!

코멘트 내용에는 십분 공감합니다!
Next.js의 [Font API](https://nextjs.org/docs/app/building-your-application/optimizing/fonts#google-fonts)에서 Google Fonts로 사용하려고 할 때 프리텐다드가 없어서 아쉽더라고요...
