### ISSUE TITLE
메모장에서 글꼴 깨짐 현상

### ISSUE THREAD

**Issue by AlphaBs** [orioncactus/pretendard#201]
![image](https://github.com/orioncactus/pretendard/assets/17783561/50be52e3-2322-4f44-a12f-dcbad2de19e4)

웹브라우저나 워드패드에서는 폰트가 잘 출력이 되는데 윈도우 11 메모장에서는 폰트가 제대로 출력이 되지 않는 것 같습니다. 일부 획이 과도하게 굵게 보입니다.  

메모장의 문제인지 폰트의 문제인지는 잘 모르겠습니다만 나눔고딕으로 테스트를 해 보았을때에는 메모장에서도 출력이 잘 됩니다.

![image](https://github.com/orioncactus/pretendard/assets/17783561/8c051355-617c-40ca-81b1-9af278dbf01f)

**Comment by kms0219kms** [comment]
이 부분은 MS ClearType의 문제로 많이 알려져있고 폰트의 문제라고 보기는 어렵습니다.
나눔고딕도 지금 올려주신 사진에서 자세히 보시면 이런 폰트의 일그러짐과 번짐이 보입니다.

**Comment by AlphaBs** [comment]
답변 감사드립니다. 어쩔 수 없는것같네요.
