### ISSUE TITLE
Pretendard 사용 서비스 예시 등록 

### ISSUE THREAD

**Issue by kevinOriginal** [orioncactus/pretendard#24]
안녕하세요, 저희 서비스에서 Pretendard 를 사용하고 있습니다. (점진적 도입중)
https://festa.io

혹시 사용중인 회사에 등록 가능한지 물어보고 싶어 이슈 남깁니다.
로고 같이 남깁니다.

감사합니다.

 
![Festa logo black](https://user-images.githubusercontent.com/18115360/132466040-ce1a5028-2b30-4959-abf3-868065d609b9.png)

**Comment by orioncactus** [comment]
안녕하세요! 이렇게 이슈를 등록해주셔서 감사드리며, Festa 서비스에서 Pretendard가 유용하게 쓰일 수 있어 기쁩니다 ☺️
당연히 환영입니다! 제가 readme를 업데이트하는 방법도 있으나, Pull Request를 남겨주시는 것도 기록을 위해 좋을 듯합니다. 괜찮으신 방법을 알려주시면 적용하겠습니다 :)

**Comment by orioncactus** [comment]
Pretendard를 사용하는 곳에 추가했습니다 ☺️
