### ISSUE TITLE
한글 글리프의 크기 조정

### ISSUE THREAD

**Issue by quiple** [orioncactus/pretendard#27]
안녕하세요! 제작해주신 폰트 감사히 사용하고 있습니다.

다만 본고딕의 한글 크기가 커서 조정을 하셨음에도 불구하고 아직도 라틴 문자보다 한글이 커 보이는 경향이 있는 것 같아서 요청드립니다.

![apple](https://user-images.githubusercontent.com/11014257/134344846-b832527b-a981-4e1b-85e3-e3bc54f746ea.png)
이게 Apple 홈페이지에 텍스트를 수정해 캡처한 이미지고 (제가 Mac이 없어서)

![pre](https://user-images.githubusercontent.com/11014257/134344868-c1954781-9179-4688-9bd2-d035c3abd3e1.png)
이게 Pretendard입니다.

보시다시피 Apple의 것과 비교해서 한글의 높이가 라틴 문자보다 살짝 더 큰 게 눈에 띄는데 한글의 크기를 조금만 더 줄여주시면 좋지 않을까 생각합니다.

![pre](https://user-images.githubusercontent.com/11014257/134348239-f737b139-1872-4048-be6a-81a354c59222.gif)
GIF 이미지입니다. 배경색이 짙은 것이 Apple입니다. 둘 다 크기 720px, 굵기 400입니다.

감사합니다!

**Comment by orioncactus** [comment]
안녕하세요! Pretendard의 가독성 개선을 위해 이렇게 참고 이미지를 포함해 소중한 피드백을 남겨주셔서 진심으로 감사드립니다.

Pretendard는 Apple의 system-ui 환경에 가능한 맞춘 글꼴로, macOS의 San Francisco와 Apple SD 산돌고딕 Neo의 섞어쓰기 환경을 바탕으로 제작되었습니다. 따라서 Apple SD 산돌고딕 Neo 단독일 때, 그리고 San Francisco + Apple SD 산돌고딕 Neo일 때의 섞어쓰기 비율과 크게 다름이 없으며, 이 비율은 Apple에서 iOS 6의 한글 본문 글꼴로 Apple SD 산돌고딕 Neo를 채택할 때 산돌고딕 Neo1에서 비율이 조정되어 나온 것을 당시 iOS 6 기본 글꼴이었던 Helvetica Neue에 맞춘 것이 아닐까 추측하고 참고한 것입니다. 그러나 말씀하신 것처럼 이렇게 조정한 비율은 한글과 영문이 완벽하게 보여지기 위한 절대적 기준은 아니며, 이미지로 올려주신 것처럼 Apple 한국 웹사이트에서는 macOS에서 쓰이는 Apple SD 산돌고딕 Neo와 San Francisco에서 굵기와 크기를 다르게 조정한 글꼴을 쓰고 있고, 또 비슷한 문제에서 시작된 Toss Product Sans도 나온 상황을 감안하면 얼마큼 해결이 필요한 상황이기도 합니다.

그러나 첫째로는, Pretendard는 제가 그동안 봐 온 제품 개발 환경에서 플랫폼마다 서로 달라지는 글꼴의 변화를 최소화해 추가적인 작업을 줄이고자 함이 제가 가장 바라며 신경을 쓰고 있는 부분이며, 둘째로는 영문을 한글에 맞춰 다듬었을 때 영문의 굵기나 크기 등이 영문을 주로 쓰는 문화권과는 달라져 국제적 타이포그래피 환경과 서로 대치된다는 점입니다. 이러한 흐름을 고려했을 때 Pretendard는 한글에 완벽한 글꼴이기보다는 처음에 잡아두었던 system-ui 대체 글꼴의 방향으로 가는 것이 더 많은 환경에서 Pretendard를 이롭게 쓸 수 있는 것은 아닐까 기대하고 있습니다.

말씀하신 질문에 도움이 되진 못했으나, 제 답변이 Pretendard 사용에 도움이 되었으면 좋겠습니다. 

또 다른 질문이 있으시면 언제든지 남겨주세요!
감사합니다.

**Comment by quiple** [comment]
그렇군요, 이해했습니다. 답변 감사합니다!
