### ISSUE TITLE
오픈타입 기능: 한글에 맞춘 가운뎃점을 한자 및 가나에도 적용

### ISSUE THREAD

**Issue by quiple** [orioncactus/pretendard#28]
안녕하세요! 감사히 사용하던 중에 또 궁금한 점이 생겨 요청드립니다.

제가 Pretendard를 본고딕 JP와 섞어쓰고 있는데 font-feature-settings: 'ss05'를 적용해도 일본어 문장에서 가운뎃점이 기존처럼 아래쪽에 출력되더라고요.

제가 오픈타입 기능에 대해선 잘 모르지만 '한글에 맞춘 가운뎃점'이라고 되어 있었으니 한글 문장에만 적용되는 것인가 싶었는데요, 그게 맞다면 이걸 일본어나 중국어 문장에도 적용되게 해주셨으면 좋겠습니다.

감사합니다!!

**Comment by quiple** [comment]
추가적으로 '‥'(U+2025)도 가운데로 가게 해주셨으면 합니다.

![화면 캡처 2021-09-24 035131](https://user-images.githubusercontent.com/11014257/134566565-4e4d079e-94e5-448c-a3c4-d671007feda8.png)
'‥'도 '…'와 마찬가지로 한국에서 만들어진 여타 한글 폰트에서는 가운데로 표시합니다. (사진은 산돌고딕Neo1입니다)

**Comment by orioncactus** [comment]
안녕하세요! 추가가 필요한 부분을 알려주셔서 감사드립니다. 말씀하신 글리프도 가운데 세트를 추가해두겠습니다.

생각해보니 한글에 맞춘 가운뎃점이 아니고 한글에 맞춘 줄임표가 맞네요 🥲 ss05 스타일 세트는 줄임표를 가운데에 두는 CJK 문화권을 제외하면 전부 아래로 두는 것이 일반적이라 줄임표 앞이나 뒤에 한글이 있을 때만 동작하도록 설정했는데요, 전역적으로 가운데 줄임표를 사용하시려면 'cv12'를 활성화하는 방법이 있습니다.

혹시 Character Variants를 사용하지 못하는 환경이라면 답글을 남겨주세요! 다음 개선에 참고하려 합니다 (o´〰`o)

**Comment by quiple** [comment]
답변 감사합니다! 그런데 'cv12'를 활성화하면 라틴 문자 뒤에서도 가운데로 가버려서요..
'ss05'를 한글 말고도 한자나 가나가 앞이나 뒤에 있을 때에도 동작하게 하는 건 오픈타입 기능 상에서 구현하기가 어려울까요?
물론 'cv12'를 쓰려면 쓸 수는 있지만 일본어나 중국어가 사용된 특정 부분에만 따로 스타일을 추가하기가 번거로워서요😓

**Comment by orioncactus** [comment]
OpenType 기능은 글꼴에 포함된 글리프에만 적용할 수 있기 때문에, 당장은 cv12를 활성화하는 것을 제외하면 Pretendard에 없는 가나와 한자 사이에 가운데 줄임표를 자동으로 적용하는 방법은 없습니다 🥲

다른 방법으로 ss05에서 기본 줄임표를 가운데로 맞추고, CJK 문자를 제외한 라틴, 숫자, 다른 문자 앞 뒤에 기존 줄임표를 적용하는 것을 생각해봤는데 좋은 해결 방법은 아닌 듯하고, 올해 중 적용을 고려하고 있는 가나 지원에서 말씀하신 부분을 1차적으로 적용하고, 또 나아가 한자까지 적용했을 때 불편한 부분을 모두 해소할 수 있을 듯합니다.

따라서 이 이슈는 CJK 지원을 마침과 함께 해결해 종결하도록 하겠습니다.

또 다른 질문이 있으시면 언제든 알려주세요! 감사합니다!

**Comment by quiple** [comment]
아아 그랬군요.. 포함된 글리프에만 적용되는 줄 몰랐네요😅
자세한 답변 감사합니다!

**Comment by orioncactus** [comment]
@quiple 알려주신 ‘‥’ 글리프도 말줄임표와 같이 한글에 맞게 가운데로 적용하고 있는데요, 사용 예를 보니 목차에서 목차와 번호 사이에 쓰는 문자라고 하는데, 혹시 한국에서 ‘‥’나 ‘․’를 쓰는 또다른 경우나 예시를 아시나요? 스크린샷으로 알려주신 (‥) 같은 예시를 사실 본 적이 없어 어느 때에 쓰이는지 알면 적용하는 데 도움이 될 듯합니다 👀

**Comment by quiple** [comment]
> @quiple 알려주신 ‘‥’ 글리프도 말줄임표와 같이 한글에 맞게 가운데로 적용하고 있는데요, 사용 예를 보니 목차에서 목차와 번호 사이에 쓰는 문자라고 하는데, 혹시 한국에서 ‘‥’나 ‘․’를 쓰는 또다른 경우나 예시를 아시나요? 스크린샷으로 알려주신 (‥) 같은 예시를 사실 본 적이 없어 어느 때에 쓰이는지 알면 적용하는 데 도움이 될 듯합니다 👀

용법은 말줄임표랑 동일한데 그냥 점이 두 개일 뿐인 거라고 생각했어요. 점 하나짜리(U+2024)는 잘 모르겠네요. 하나짜리는 한글 폰트들에 글리프가 아예 없는 것 같더라고요..

점 두개짜리를 제가 직접 본 예시로는 역전재판이라는 게임에서 말줄임표로 사용되는 걸 봤었거든요. 다른 예시는 잘 모르겠네요. 😅

**Comment by orioncactus** [comment]
상세한 설명 감사합니다! 다음 릴리즈 때 말씀하신 부분들을 적용하겠습니다 ☺️
