### ISSUE TITLE
npm 패키지화

### ISSUE THREAD

**Issue by archlabx** [orioncactus/pretendard#39]
npm 패키지로 릴리즈하면, `npm install pretendard` 명령으로 프론트엔드 개발에 사용 가능합니다.

좋은 폰트 제작에 감사드립니다.

**Comment by orioncactus** [comment]
안녕하세요!

이전에 걸림돌이었던 빌드 프로세스가 어느정도 정리된 듯해 Pretendard 개선과 함께 패키지를 통한 배포도 진행하려고 합니다. 다만 배포를 진행하는 데까지 시간이 조금 걸릴 듯해 정확히 언제 배포될지는 모르겠으나, npm 등 패키지로 제공을 마무리하면 이 이슈도 종결로 처리해두겠습니다.

추가적으로 궁금하신 부분이 있으시면 언제든 알려주세요. Pretendard을 아껴주셔서 감사드립니다 ☺️

**Comment by orioncactus** [comment]
이제 아래와 같은 패키지 매니저에서 사용하실 수 있습니다. 이 이슈는 이제 종결로 처리하겠습니다. 배포를 도와주신 @victorrica님께 진심으로 감사드립니다!

-   [npm](https://www.npmjs.com/package/pretendard)

```bash
npm i pretendard
```

-   [Yarn](https://yarnpkg.com/package/pretendard)

```bash
yarn add pretendard
```
