### ISSUE TITLE
원에 들어간 숫자의 크기가 이상함

### ISSUE THREAD

**Issue by cog25** [orioncactus/pretendard#43]
![image](https://user-images.githubusercontent.com/74242561/146680493-d1524824-f093-48b3-84e4-8985db0ef40b.png)
Firefox에서 Pretendard 폰트를 적용하고 본 모습입니다. 이외에도 한/글에서 동일한 문제가 발생했습니다.
```
⓪
①②③④⑤⑥⑦⑧⑨⑩
⑪⑫⑬⑭⑮⑯⑰⑱⑲⑳
㉑㉒㉓㉔㉕㉖㉗㉘㉙㉚
㉛㉜㉝㉞㉟㊱㊲㊳㊴㊵
㊶㊷㊸㊹㊺㊻㊼㊽㊾㊿
```

**Comment by orioncactus** [comment]
안녕하세요! Pretendard를 아껴주시고 확인을 위해 글리프를 정리해주셔서 감사합니다.

1.2 버전을 기준으로 모든 Pretendard 웹폰트에는 ⓪에서 ⑳까지의 글리프가 포함되어 있습니다. 해당 버전이 [최신 버전](https://github.com/orioncactus/pretendard/releases/latest)이 맞는지요?
또한 Firefox에서 최신 버전 Pretendard를 확인해보았으나 다른 브라우저와 동일하게 정상적으로 표시되는 듯합니다. 최신 버전으로 업데이트한 뒤에도 문제가 있다면, URL을 알려주시면 한 번 확인해보겠습니다.

감사합니다.

**Comment by cog25** [comment]
21번 숫자부터 fallback 폰트를 불러오는걸로 확인했습니다. 감사합니다
