### ISSUE TITLE
brew install font 등재

### ISSUE THREAD

**Issue by gintering1000** [orioncactus/pretendard#46]
안녕하세요. 아래의 Google Font 등록은 잘보았습니다.
저 또한 brew ( 패키지 관리자 ) 의 font 패키지 등록 원하는데,
혹시 제가 그것을 진행을 해봐도 될런지요?

**Comment by cog25** [comment]
해당 내용은 [Discussions/Q&A](https://github.com/orioncactus/pretendard/discussions/categories/q-a)에서 논의하는 게 좋을 것 같습니다.

**Comment by orioncactus** [comment]
안녕하세요! Pretendard를 아껴주시고 brew 패키지 등록을 위해 흔쾌히 의견을 남겨주셔서 진심으로 감사드립니다 ☺️

패키지로 등록한 뒤 관리자 설정이나 버전 업데이트 등의 패키지 관리는 어떤 식으로 진행이 되련지요? 기여해주시면 너무나 영광이나, 혹여나 번거로우시다면 제가 방법을 찾아볼 수도 있을 듯합니다.

또한 @cog25 님의 의견도 감사드립니다. 만약 brew 패키지화가 완료된다면 이것도 해결 가능한 이슈로 그대로 남겨두어도 괜찮을 것 같습니다.

**Comment by gintering1000** [comment]
안녕하세요!
패키지 관리자 등재는 보통 소스코드 내부에 등재설정파일을 넣어두고 해당 패키지관리자에 등록하는 방법이 사용됩니다.
하지만 기존에 가장 일반적인 방법은

brew에서 폰트 관리를 하는 cask-font 라는 패키지가 이미 있고 해당 패키지 주인에게 pretended를 넣어달라고 하는게 가장 좋은 방법 같습니다.

하지만 생각해보니!
나눔폰트의 등재는 구글폰트사이트의 주소를 이용해 등재가 되었고~
pretended는 github주소를 기준으로 할것인지~
구글폰트에 등록되면 등록 후의 주소로 할것인지 ( 이것이 더 장기적으로 나을 듯 합니다 )
를 고민해보시고 전략적으로 선택해보시면 될듯합니다.


brew-nanum-gothic의 패키지 정보


사람들이 보통 brew를 통해 설치하는 방법



homebrew-cask-fonts <https://github.com/Homebrew/homebrew-cask-fonts> : 위의 homebrew/cask-font 패키지 github 주소
나눔 예시 <https://github.com/Homebrew/homebrew-cask-fonts/blob/HEAD/Casks/font-nanum-gothic.rb> : homebrew/cask-font 내부의 나눔패키지 관리

**Comment by kms0219kms** [comment]
이 부분은 저도 기여가 가능한 부분입니다.
혹시나 저도 brew font에 등재할 수 있도록 request를 보내려고 하는데 어떻게 생각하시나요?
아직은 Pretendard가 request 되지는 않았습니다.

**Comment by kms0219kms** [comment]
아, Google Fonts에 등재된다면 본 패키지화가 자동으로 진행된다고 합니다. [#](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/CONTRIBUTING.md)

저는 본 폰트가 Google Fonts에 등재될 계획에 있는 것으로 알고 있습니다.

따라서 Google Fonts에 등재되면, 자동으로 패키지화가 되게 되므로 이 이슈는 #7 과 같이 진행되면 될 것같습니다.
