### ISSUE TITLE
눈누 웹폰트 사이트와 본 공식 Repository의 웹폰트의 배포 방식 차이로 인한 폰트가족 분할 문제

### ISSUE THREAD

**Issue by kms0219kms** [orioncactus/pretendard#50]
[눈누 웹폰트](https://noonnu.cc/font_page/698)에 올라온 Pretendard는, 
먼저 웹폰트 번들이나 다이나믹 웹폰트 형태가 아닌 직접 다운로드 하여 호스팅하는 방식으로 
제공되고 있어 눈누를 사용하는 경우 직접 css 작업을 해야하는 점이 있으며,

또한 폰트가족도 각 굵기마다 다르게 업로드 되어있어 굵은 글씨의 경우 수동으로 Pretendard-Bold로 지정해야합니다.
이런 불편함을 줄이기 위해 눈누에 문의하여 공식으로 배포되는 다이나믹 웹폰트를 업로드하고, 폰트가족을 하나로 합쳐 사용자의 불편함을 줄였으면 합니다.

실제로 본고딕도 이런 절차로 구글폰트에서 제공하는 다이나믹 웹폰트로 교체된 바 있습니다.

**Comment by orioncactus** [comment]
안녕하세요! Pretendard에 관심을 가져주시고 눈누에서 원활히 사용할 수 있도록 의견을 남겨주셔서 감사드립니다.

확인해보니, 재밌게도 Pretendard 관련 [눈누 Github 레포지터리](https://github.com/Project-Noonnu/noonfonts_2107)를 확인해보니, 모든 font-weight가 포함된 [pretendard.css](https://github.com/Project-Noonnu/noonfonts_2107/blob/master/pretendard.css)가 올려져 있더라구요. 말씀하신 것처럼 해당 css로 Pretendard를 편리하게 제공하는 것은 어떤지, 또는 파편화 방지를 위해 눈누 레포지터리를 통한 웹폰트 제공이 아닌, Pretendard 레포지터리에서 제공하는 웹폰트 서빙 방법으로 제공하는 것은 어떤지 눈누에 확인해보겠습니다.

또한 별다른 업데이트 없이 최신 버전 Pretendard 웹폰트를 사용하시려면 눈누에서 제공하는 방법이 아닌 [Pretendard GitHub Readme](https://github.com/orioncactus/pretendard#%EC%9B%B9%ED%8F%B0%ED%8A%B8)에서 안내하는 웹폰트 사용 방법을 확인해보시는 것을 추천드립니다. 특정 버전을 안정적으로 사용하시려면 `https://cdn.jsdelivr.net/gh/orioncactus/pretendard@1.2.1/dist/web/static/pretendard.css`와 같이 쓰시는 것도 가능합니다.

**Comment by kms0219kms** [comment]
네, 저도 아무래도 해당 깃허브 레포지터리를 보고, 최신 버전 웹폰트로 업데이트가 쉽지 않겠다 싶어 이 이슈를 생성하였습니다.
아무래도 버전이 업데이트 되면 눈누에서 항상 업데이트를 반영할리가 만무하니,
눈누 레포지터리를 통한 웹폰트 제공이 아닌, Pretendard 레포지터리에서 제공하는 웹폰트 서빙 방법이 나을거 같다고 생각합니다.

**Comment by kms0219kms** [comment]
또한 눈누 레포가 아닌 눈누 홈페이지에서는 해당 css를 사용하지 않고 하나하나 파편화된 폰트가족으로 배포되고 있습니다...ㅠㅠ

깃허브 레포지토리를 뒤져볼 생각을 하지 않고서야 직접! 하나하나 font-face 정의를 해야해서 불편할 것 같습니다.

**Comment by orioncactus** [comment]
의견을 남겨주셔서 감사드립니다! 눈누에 의견을 남겨보고, 상황에 어느정도 진전이 있으면 이 이슈를 통해 공유드리겠습니다! ✧٩(•́⌄•́๑)و ✧

**Comment by orioncactus** [comment]
안녕하세요! 이 이슈를 올려주신지 벌써 두 달이나 넘었네요. 방금 눈누에 문의를 올렸으며, 답장이 오거나 진전이 되면 여기에 공유드리겠습니다. 기다려주셔서 감사드립니다 ☺️

**Comment by orioncactus** [comment]
눈누 담당자분으로부터 업데이트 예정이라는 답장을 받은지 꽤 되었으나, 아직 업데이트가 되어있지 않네요 🥲 며칠 더 지켜보고 다시 메일로 전달드려보겠습니다.

**Comment by kms0219kms** [comment]
수정이 된것을 확인했습니다. 이슈 닫겠습니다.
