### ISSUE TITLE
jsDelivr와 cdnjs로 CDN을 이중화하는 방안

### ISSUE THREAD

**Issue by kms0219kms** [orioncactus/pretendard#51]
jsDelivr에 깃허브를 통해 배포되면 아직 릴리즈 되지 않았지만 바로 배포되버리는 안정성 확보 문제가 있습니다.

Pretendard는 npm과 yarn으로도 배포되니 jsDelivr에서 npm을 통해, 릴리즈 된 경우 배포되는 방식으로 배포하거나

cdnjs과 같이 jsDelivr보다 속도와 캐싱 등 다른 문제가 적은(다시 말해 #35 등의 문제가 적은) 플렛폼으로 배포하는 것이 어떤지 여쭙고 싶습니다.

참고로, cdnjs는 npm이 배포되있으면 별다른 큰 작업 없이 업로드 작업이 가능하며, 이는 제가 기여가 가능합니다.

**Comment by hiddenest** [comment]
@kms0219kms 안녕하세요! 해당 CDN 작업을 했던 사람입니다 :)
저도 해당 작업을 하면서 어떤 서비스를 통해 연동을 하면 좋을지 고민을 하였고, 아래의 포인트를 잡았습니다.

1번. 한국 Region 내에서 빠른 속도로 제공되는가?
> jsDelivr는 cloudflare, fastly, stackpath, quantil, AWS(앞의 4개가 모두 장애났을 때 fallback)을 사용합니다.  
> jsDelivr는 더 넓은 네트워크에서 가장 가까운 Region을 찾아 서빙하는 구조로 되어있기 때문에, jsDelivr가 cdnjs보다 빠른 속도로 제공된다고 볼 수 있습니다.

2번. 배포를 위한 별도의 관리 작업이 적은가?
> Pretendard는 GitHub의 Release를 통해 배포되는 구조이며, 이는 cdnjs 및 jsDelivr 모두 동일한 방식으로 반영됩니다.  
> 그렇다면, 프로덕션 반영 주기 혹은 Cache의 강제 Purge 유무를 확인하고자 했는데, cdnjs에서는 별도의 Purge method를 찾지 못하였습니다 😇 

추가.
말씀해주신 바로 배포되는 문제는 URL에서 `pretendard@main` 등 main 브랜치를 직접적으로 바라볼 때 발생하는 문제로 인지하였습니다.  
현재 사용중인  `pretendard@latest` 로 로드를 하면, GitHub Release 기준으로 가장 최신 릴리즈 내역을 가져오게 됩니다.

---

우선 제가 jsDelivr를 도입할 때 확인했던 내용을 말씀드렸습니다.
혹시 제가 잘못 알고 있는 내용이 있다면 알려주시면 감사하겠습니다!
\+ cdnjs에도 배포를 해서 이중화 처리를 해놓는 것도 좋은 아이디어일 것 같습니다 👍🏻

**Comment by kms0219kms** [comment]
## 1번에 관련한 첨언
jsDelivr도 많은 서버가 있어 빠르게 제공되나,

cdnjs가 개발자들끼리는 더욱 유명한 cdn 서비스 이고,

cdnjs는 Cloudflare가 직접 호스팅하고 또한 각 사용하는 사용자의 자원도 공유하며 jsDelivr보다 안정적인 호스팅을 제공합니다.
(즉, cdnjs가 사용자가 더 많으며, 그 cdnjs에서 파일을 받아 사용하는 End User쪽에서, 다른 사이트에 cdnjs로 파일을 받을 때 자원을 빠르게 공유받는다는 의미입니다.)

또한, cdnjs와 jsDelivr를 교차하여 cdn을 사용하는 경우(ex. Bootstrap과 해당 vendor들), cdnjs가 속도가 더 빠릅니다.

그리고 Cloudflare에서 직접 호스팅하다보니 spdy + http/2.0 프로토콜을 우수히 지원하기 때문에, 병렬로 cdn이 로드될 때 훨씬 빠른 서비스를 제공합니다.

## 2번에 관련한 첨언
cdnjs에서 별도의 purge method가 없는 이유는, npm에서 항시 배포되기 때문에, 
github에서 jsdelivr로 반영되는것이 가장 많은 자원을 소모(주기가 짧아서)하나
npm이나 github release의 반영이 주기가 길다보니 자원이 적어 purge 하지 않아도, 반영 주기보다 짧게 캐시하니 큰 문제가 되지 않아서 입니다.

## 이중화 관련 의견
jsDelivr도 호스팅하여 이중화 하여 간혹 있는 Cloudflare&AWS의 장애시에도 대처 할 수 있을거 같아 이중화하는 것에 찬성합니다.

**Comment by hiddenest** [comment]
@kms0219kms 
좋은 정보 감사합니다! 저도 관련 내용이 궁금해서 조금 더 찾아보았습니다.  
몇 가지 정보를 조금 더 체크하여 정리하면 다음과 같습니다.

- jsDelivr의 경우 http/2와 SPDY를 모두 지원하고 있습니다.
- jsDelivr는 Cloudflare, fastly 등의 fallback 망이 있습니다. [How jsDelivr Works](https://www.jsdelivr.com/network/infographic)
- cdnjs는 Cloudflare 위에서 동작합니다.
- 속도 측면에서는 둘이 비슷할 것으로 예상하나, cdnjs가 Cloudflare에서 직접 회선을 연결해 가져올 것이므로(인천 경유), 우회해서 한국으로 들어오는 jsDelivr보다 조금 더 빠를 수 있습니다.
- Vue, Bootstrap 등이 jsDelivr를 공식 CDN으로 사용하고 있어, 안정성이 낮다고 볼 수는 없을 것 같습니다.
- cdnjs는 전체 웹의 12.5%에 달하는 트래픽을 감당하고 있습니다. (공식 홈페이지 내용)
- cdnjs와 jsDelivr의 경우 npm, GitHub 기준으로 유사한 캐시 및 업데이트 정책을 취하고 있습니다. (특정 시간이 지날 때마다 업데이트)
- cdnjs의 사용률이 jsDelivr보다 높다는 통계 자료들이 있습니다.
- CDN에 등록하기 위해 cdnjs는 PR을 보내야 하며, jsDelivr는 주소에 source/package name/version을 넣어 접속하면 됩니다.

그렇다면, 정리된 내용을 바탕으로, 말씀해주신 릴리즈의 안정성 확보를 위해 cdnjs를 사용하는 것이 좋은지는 약간 고민이 있습니다.  
cdnjs를 사용하는 것이 jsDelivr보다 '안정성이 높다'고 볼 수 있는 자료들이 적기 때문입니다.

하지만, kms0219kms님께서 말씀해주신 부분을 고려했을 때,  
cdnjs에 등록된다면 더 많은 개발자분들께서 Pretendard를 사용할 수 있을 것 같다는 생각이 들었습니다!

그렇다면, 혹시 kms0219kms님께서 cdnjs에 PR을 보내 등록을 해주실 수 있으실까요?

**Comment by hiddenest** [comment]
@kms0219kms 감사합니다! 👍🏻 👍🏻 👍🏻

**Comment by kms0219kms** [comment]
[cdnjs/packages #975](https://github.com/cdnjs/packages/issues/975) Request를 넣었습니다.
자세히 알아보니 PR이 아니라 이슈를 보내면 되서, 이슈로 보내드렸습니다

**Comment by kms0219kms** [comment]
어? 홈페이지에는 이슈를 남기라고, 깃허브에는 PR을 남기라고 되어있네요 🤣 혹시 모르니 PR도 함께 넣어보겠습니다

**Comment by kms0219kms** [comment]
이 세상엔 참 CDN이 많은 거 같습니다.
cdnjs 말고, unpkg에 이중화 해보는 것도 좋을거 같네요

**Comment by kms0219kms** [comment]
unpkg는 따로 Request가 필요없는 지라, 지금 당장에 사용이 가능하다는 장점이 있고, cdnjs처럼 클플위에서 돌아가 속도 문제도 적어보입니다.

**Comment by kms0219kms** [comment]
Directory: https://unpkg.com/browse/pretendard@1.2.1/

**Comment by orioncactus** [comment]
안녕하세요! 답장이 늦는 동안 멋지게 풀어주셨네요 🥺 먼저 이중화 방안에 대해 꼼꼼하게 제안해주시고 cdnjs에 request 및 UNPKG로부터 Pretendard를 쓸 수 있게 기여해주신 @kms0219kms 님께 너무나 감사드리며, 제가 잘 알지 못하는 부분에 대해 더 나은 방안을 멋지게 알려주신 @hiddenest 님께도 진심으로 감사드립니다!

정리하면, jsDelivr를 포함해 UNPKG, cdnjs 세 CDN으로부터 Pretendard를 사용할 수 있게 되는 것인가요? 또 cdnjs에서 올려주신 request가 마무리되면 그 때 함께 Readme를 업데이트해도 괜찮은지 알려주시면 감사하겠습니다!

**Comment by kms0219kms** [comment]
cdnjs request가 마무리되면, readme에 cdnjs로 등재할 수 있습니다.
아직까지는 unpkg가 완전히 캐시된게 아니라, 조금 속도가 느려서 캐시가 완전히 될때쯤 cdnjs에 마무리가 될거 같아요.

**cdnjs 마무리되면 unpkg, cdnjs, jsdelivr에서 사용할 수 있다고 readme 수정하시면 될거 같아요.**

**Comment by kms0219kms** [comment]
[cdnjs/packages #975 1017199028](/cdnjs/packages/issues/975#issuecomment-1017199028) 과 같이, 기본적으로 포함되어야 하는 최신버전 css리스트를 전송하였습니다.

![image](https://user-images.githubusercontent.com/67222970/150295811-1e76f5d5-09a5-4431-9505-b52bc83b09de.png)

**Comment by kms0219kms** [comment]
unpkg의 빠른 캐싱을 위해 제 개인 프로젝트에, unpkg로 Pretendard를 종류별로 import하여 빠르게 캐시하도록 진행중입니다!

캐시 중일때는 속도가 현저히 느리지만 캐시가 끝나면 빠른속도로 로드가 됩니다!
![image](https://user-images.githubusercontent.com/67222970/150296578-b9795977-2ab5-41da-b2e9-d73a166369c1.png)

**Comment by kms0219kms** [comment]
현재 90개의 서브셋 중, Regular만 90개 모두 캐시 작업이 28개 서브셋을 남기고 완료되었습니다.

**Comment by gintering1000** [comment]
등재는 다다익선. 하지만 개발자 입장에서는 프로토타입? 메인타입? 같은 개인이 선호하는 메인 등재를 하나 선택해서 올린후에 이중화 삼중화 하시면 될듯합니다. ( 예제 : 저의 휴대폰 메인 플랫폼은 아이폰이지만, 안드로이드, 구글폰도 서브로 가지고 있습니다 )

**Comment by gintering1000** [comment]
등재는 다다익선. 하지만 개발자 입장에서는 프로토타입? 메인타입? 같은 개인이 선호하는 메인 등재를 하나 선택해서 올린후에 이중화 삼중화 하시면 될듯합니다. ( 예제 : 저의 휴대폰 메인 플랫폼은 아이폰이지만, 안드로이드, 구글폰도 서브로 가지고 있습니다 )

**Comment by kms0219kms** [comment]
@orioncactus 드디어 cdnjs에 업로드되었다고 합니다.
https://cdnjs.com/libraries/pretendard

**Comment by kms0219kms** [comment]
#56 PR 올려드렸습니다

**Comment by orioncactus** [comment]
신경써주셔서 감사드립니다! PR 확인하겠습니다 🔥
