### ISSUE TITLE
mac 환경에서 적용이 안 됩니다.

### ISSUE THREAD

**Issue by Newri620** [orioncactus/pretendard#58]
윈도우 환경에서는 어떤 브라우저로 접속해도 적용되지만, 
mac에서 pretendard 폰트가 적용되지 않습니다.

**Comment by orioncactus** [comment]
안녕하세요! 종결로 처리되었지만 참고로 덧붙이자면, Safari에서는 Local에 있는 글꼴이라도 font-face를 통해 로컬 이름을 지정해주지 않으면 웹폰트로 표시되지 않습니다. 해당 이슈가 있다면, font-face와 웹폰트 경로를 정상적으로 설정하면 됩니다.
