### ISSUE TITLE
iOS 15.4 업데이트 이후에 다이나믹 서브셋 사용 시 `&nbsp;` 이슈

### ISSUE THREAD

**Issue by egaoneko** [orioncactus/pretendard#59]
안녕하세요! 우선 만들어주신 폰트를 잘 사용하고 있습니다.

다름이 아니라 이번 iOS 15.4 버전 업데이트 이후에 다이나믹 서브셋을 사용할 때 Safari 및 Chrome 등 브라우저에서 `&nbsp;`에 이상한 문자가 노출되어 문의드립니다.

![image](https://user-images.githubusercontent.com/6583941/158515540-f6a32f82-15fe-4ba9-b332-eb77a8fd8efa.png)

상단의 이미지와 같이 가로줄로 된 특이한 문자가 노출되는데요. 다이나믹 서브셋 대신 전체 폰트를 사용하게 되면 해당 이슈가 재현되지 않아서 문의드립니다.

**Comment by orioncactus** [comment]
안녕하세요! 이렇게 빠르게 제보해주셔서 감사드립니다. 알려주신 문제는 Internet Explorer에서도 동일하게 발생하지만, 모던 브라우저에서는 보이지 않아 크게 고려하지 않았던 문제인데요, 새 iOS 버전 및 다이나믹 서브셋을 사용하고 있는 대부분의 웹사이트에서 발생하는지 파악할 수 없지만, 문제가 있다면 영향을 받는 곳이 상당할 듯해 오늘 집에 도착해 바로 확인해보려고 합니다.

우선 집에 도착하기 전에, 다이나믹 서브셋을 사용하고 있는 [Flex](https://flex.team)에서 iOS 15.3.1 및 iOS 15.4에서 각각 비교해보았는데요, 다행히 동일한 문제가 보이지 않는 것을 보아 font-family를 2개 이상(system-ui, sans-serif 등) 설정하면 정상적으로 표시되지 않을까 예상해봅니다.

**Comment by egaoneko** [comment]
맥북을 15.4로 업데이트해도 동일하게 발생하네요.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/6583941/158599300-fbf5c0b8-a043-4285-9b2f-f499c55fc552.png">

**Comment by orioncactus** [comment]
꼼꼼하게 확인해주셔서 감사합니다! macOS를 12.3으로 업데이트하면 시간이 오래 걸릴 듯해, 혹시나 Safari Technology Preview 최신 버전에서 말씀하신 것처럼 `&nbsp;`를 넣어 확인해보니 문제가 확인되어서, 해결 방법이 있는지 빠르게 확인해보고 알려드리겠습니다.

**Comment by orioncactus** [comment]
문제를 찾아 해결했습니다. 이유와 해결한 방법은 다음과 같으며, 한 시간 안에 반영할 예정입니다. 이렇게 문제를 빠르게 알려주시고 해결할 수 있도록 도와주셔서 정말 감사드립니다! 이 이슈는 다이나믹 서브셋이 다시 정상적으로 작동되면 종결 처리하겠습니다.
- dynamic-subset 디렉터리에 있는 subset.89 파일에는 `&nbsp;`를 쓸 때 표시되는 `nbspace(u00A0)` 글리프가 포함되어 있으나, pretendard-dynamic-subset.css에서 정상적으로 unicode-range가 있음에도 해당 글리프가 제외되어 표시됨
- 이번 Safari 업데이트로 `&nbsp;`에 해당하는 글리프가 `space(u0020)`에서 `nbspace(u00A0)`으로 업데이트된 것으로 예상
- 그렇게 nbspace가 표시되지 않아, 없는 글리프인 .notdef(가로줄 모양)이 표시된 문제
- 따라서 nbspace가 포함된 서브셋 파일(subset.91)을 새로 추가한 다음, pretendard-dynamic-subset.css에서 subset.89 대신 subset.91을 통해 nbspace를 불러오게 해 해결

**Comment by egaoneko** [comment]
작게 나마 도움이 될 수 있어서 기뻤습니다. 이렇게나 빨리 수정해주시고 상세하게 설명도 해주셔서 감사합니다! 🙏

**Comment by egaoneko** [comment]
@orioncactus 안녕하세요~ 말씀해주신 내용을 적용해보았는데요. 해당 현상이 지속되어 공유드립니다.
혹시나 캐시 이슈일까 하여, 재차 확인해보았는데 말씀해주신 추가된 91번을 호출해도 없는 글리프로 노출이되네요.

<img width="260" alt="image" src="https://user-images.githubusercontent.com/6583941/159258063-cea57554-7ae2-44ee-baec-c6de77f7ddcc.png">

<img width="443" alt="image" src="https://user-images.githubusercontent.com/6583941/159258147-f9015b08-5922-4b9b-802d-871253ec1e65.png">

<img width="38" alt="image" src="https://user-images.githubusercontent.com/6583941/159258180-6584d68c-ab15-4767-87ed-914babf9a7e8.png">

**Comment by orioncactus** [comment]
안녕하세요. 방금 확인해보았는데요, 말씀하신 것처럼 1.2.2 릴리즈에서 동일한 문제는 발견하지 못했습니다. iOS 15.4 및 macOS 12.3에서 확인하였으며, 테스트 방법은 다음과 같습니다. 시크릿 모드에서 접근해도 동일한지요?
1. 최신 다이나믹 서브셋이 적용된 [flex.team](https://flex.team)에서 아무 텍스트에 &nbsp;를 추가해 확인 (iOS 및 macOS)
2. 로컬에서 테스트 페이지를 만들어 확인, 아래를 각각 비교해 문제 확인
  - https://cdn.jsdelivr.net/gh/orioncactus/pretendard@1.2.1/dist/web/static/pretendard-dynamic-subset.css 
  - https://cdn.jsdelivr.net/gh/orioncactus/pretendard@1.2.2/dist/web/static/pretendard-dynamic-subset.css

**Comment by orioncactus** [comment]
혹시 다른 환경에서도 발생하는지 저도 한 번 확인해보겠습니다! 시크릿 모드에서도 발생한다니 뭔가 이상하군요 🤔 특정 weight에서 발생하는지도 확인해봤는데, 이것도 문제는 없는 듯합니다.

**Comment by egaoneko** [comment]
감사합니다! 아무래도 저희쪽에 업로드가 잘못되거나 했을 것 같습니다.

말씀해주신 [이 경로](
https://cdn.jsdelivr.net/gh/orioncactus/pretendard@1.2.2/dist/web/static/pretendard-dynamic-subset.css)를 직접 넣었을 때는 문제가 없는데 동일한 파일을 업로드해서 사용하는 부분에서는 Semibold에서만 91번을 못가져오고, 신기하게 Regular만 91번을 가져오고 있네요.

아무래도 어디선가 꼬인 것 같아서 제가 살펴보겠습니다. 늦은 밤까지 같이 확인해주셔서 감사합니다.

**Comment by egaoneko** [comment]
이슈는 잘 해결하였습니다. 최신 수정이어서 master를 가져와서 봤는데 이게 이슈였습니다. 😅
배포해주신 1.2.2 버전의 파일을 사용하니 수정해주신대로 잘 동작하였습니다~ 감사합니다!

**Comment by orioncactus** [comment]
잘 해결되었다니 다행입니다! 사용하시면서 다른 문제나 개선이 필요한 부분이 있다면 언제든지 알려주세요! (❁´▽`❁)

**Comment by kms0219kms** [comment]
https://utilnotice.sskate.me/class/

이 사이트에 화살표 아이콘이 깨져서 표시되네요.

**Comment by kms0219kms** [comment]
`&#xE001;` 로 화살표를 불러와 사용중입니다.

**Comment by kms0219kms** [comment]
아, 기존에 Spoqa 폰트에서 프리텐다드로 옮기면서 `&#xE001;` 가 지원되지 않아 발생한 문제로 확인되었습니다.

**Comment by kms0219kms** [comment]
혹시 가능하시다면 Spoqa Han Sans에 있는 특수 글리프들도 호환해 주실 수 있으신가요?
* 이 부분은 새 이슈에서 다루도록 하겠습니다,

**Comment by kms0219kms** [comment]
#63
