### ISSUE TITLE
Spoqa Han Sans에서 Pretendard로 Migration 할 때 PUA 글리프 미지원으로 인한 글자 깨짐 이슈

### ISSUE THREAD

**Issue by kms0219kms** [orioncactus/pretendard#63]
Spoqa Han Sans에서 Pretendard로 Migration 할 때,

기존에 Spoqa Han Sans에서 지원하던 PUA 공간 특수 글리프가 Pretendard에는 없어서, = 모양의 이상한 글자가 노출됩니다.

혹시 해당 PUA 글리프를 Pretendard에 추가해 주실 계획이 있으신가요?

**Comment by orioncactus** [comment]
안녕하세요! 소중한 피드백 감사드립니다. 추가하는 데 큰 어려움이 없을 듯해 조만간 배포할 버전에 반영할 수 있을 듯합니다. 혹시 추가가 필요한 글리프가 uE000(``) 및 uE001(``) 말고 또 있을까요?

**Comment by orioncactus** [comment]
문제가 있네요.
1. 모체인 Inter에서는 uE000부터 PUA를 할당해 사용하고 있어서, Spoqa Han Sans에서 사용하고 있는 Chevron 글리프와 영역이 겹쳐, 말씀하신 Chevron 글리프는 Spoqa Han Sans와 같은 유니코드가 아닌 다른 PUA에 할당해야 할 듯합니다.
2. 또한 Pretendard에서 제공하는 다이나믹 서브셋 바탕인 [Noto Sans KR](https://fonts.google.com/noto/specimen/Noto+Sans+KR)에서는 PUA에 해당하는 unicode-range이 할당되지 않았으므로, 원칙적으로는 Pretendard 다이나믹 서브셋도 마찬가지로 PUA를 지원하지 않는 것이 자연스럽습니다. 따라서 PUA를 사용하고자 하신다면 일반 Pretendard 웹폰트를 사용하시는 것을 추천드리는데요, Pretendard 다이나믹 서브셋에서도 PUA 뿐만 아니라 다른 편리한 심벌을 추가하는 것이 맞을지 검토해보겠습니다.

**Comment by orioncactus** [comment]
이번 업데이트에서는 다이나믹 서브셋에서 Chevron 아이콘을 지원하지 않기로 했습니다. 이후에 SF Symbols와 같은 확장성 있는 아이콘 심벌을 추가할 때 다이나믹 서브셋에서도 아이콘 심벌을 지원해보려고 합니다. 다이나믹 서브셋이 아닌, 다른 웹폰트 제공 방법을 통해 Chevron 글리프를 사용하실 수 있습니다. 추가된 글리프와 unicode는 다음과 같습니다:

- upChevron: uf042 ``
- downChevron: uf043 ``
- leftChevron: uf044 ``
- rightChevron: uf045 ``

마지막으로 Pretendard를 개선할 수 있도록 소중한 의견을 남겨주셔서 진심으로 감사드립니다 :D

**Comment by kms0219kms** [comment]
업데이트 해주셔서 감사합니다.
현재 해당 PUA 글리프가 필요한 곳에는 dynamic-subset이 아닌 일반 webfont css의 1.3.0 패치로 업데이트를 진행할 예정입니다.
