### ISSUE TITLE
Appie CDN(?) 관련 문의

### ISSUE THREAD

**Issue by kms0219kms** [orioncactus/pretendard#70]
https://pretendard.appie.dev/ CDN에서 Pretendard 웹 폰트를 배포 중인것을 한 홈페이지에서 발견했습니다.

해당 CDN이 정식적으로 본 레포에서 관리되고 있는것이며, 최신 버전인 1.3.0이 맞는지 확인이 가능하실까요?

**Comment by orioncactus** [comment]
안녕하세요! 말씀하신 URL이 https://pretendard.appie.dev가 맞을지요? 해당 URL에 접속할 때 `Sorry, AppieDev cannot process this request. Please check your request.` 라는 메시지가 보여 확인 방법이 있는지 여쭤봅니다 👀

**Comment by orioncactus** [comment]
`https://pretendard.appie.dev/web/static/pretendard.css` 요 경로로 제공되고 있군요! appie.dev가 Apple Fonts 관련 CDN일까요?

**Comment by kms0219kms** [comment]
Appie네요 진짜 ㅋㅋㅋㅋㅋ
전 Apple Fonts라는 곳이 있는줄 알았네요
