### ISSUE TITLE
Pretendard, Pretendard JP를 동시에 설치 한 뒤, 시스템 기본 폰트를 Pretendard로 설정 시 알수없는 일본어로 글자가 깨짐

### ISSUE THREAD

**Issue by kms0219kms** [orioncactus/pretendard#72]
Pretendard, Pretendard JP를 동시에 설치 한 뒤,

시스템 기본 폰트를 Pretendard로 설정 시 뜻을 알 수 없는 일본어로 글자가 깨지는 현상이 발생합니다.

제 생각에 해당 폰트의 폰트가족이 모두 동일하게 Pretendard 인것 같습니다.

Pretendard JP로 폰트가족을 바꿔주셔야 할 것 같습니다.

**Comment by kms0219kms** [comment]
+ Windows 11 Home K ver 22000.613

**Comment by orioncactus** [comment]
안녕하세요! Pretendard, Pretendard JP, Pretendard Std, 그리고 otf와 ttf에서 모두 name 테이블을 확인해봤는데요, 동일한 이름을 공유하고 있는 부분은 찾지 못했습니다. 발생하는 문제가 정확히 어떤지 스크린샷 등으로 확인해볼 수 있을까요?
참고로 Pretendard에서는 가타카나, 히라가나는 있으나 한자는 포함되지 않아, 일본 한자를 사용하시려면 Pretendard JP를 사용하시는 것을 추천드립니다.

**Comment by kms0219kms** [comment]
음, 윈도우 폰트를 NomeiryoUI로 변경한 뒤, Pretendard 3종을 모두 설치할 경우 일본어로 글자가 보이던데, 지금은 또 재현이 안되네요.
나중에 재현되면 다시 이슈 열겠습니다.
