### ISSUE TITLE
Windows Terminal 에서 폰트 문제

### ISSUE THREAD

**Issue by baek-sang** [orioncactus/pretendard#74]
## 문제
Pretendard 폰트 사용 시 띄어쓰기 한 것처럼 간격이 벌어짐.

## 환경
- Windows 10 21H1 / Windows Terminal Preview 1.13.10983.0 / Pretendard 1.3.0 otf,ttf 설치
- Windows 11 21H2 / Windows Terminal 1.12.10733.0 / otf, ttf

## Consolas
![w11-consolas](https://user-images.githubusercontent.com/69100154/168445444-1a2abbbb-371d-4a72-831a-b1ce37232be8.png)

## Pretendard
![w11-terminal-p](https://user-images.githubusercontent.com/69100154/168445488-55eb2a4f-b344-4ba9-bc15-e35d5c9ab792.png)

![w11-p-s1](https://user-images.githubusercontent.com/69100154/168445493-9a3d021d-4cf3-44bd-9213-436e364df9de.png)

**Comment by kms0219kms** [comment]
Monospace 글꼴이 아니므로 해당 문제가 발생 할 수 밖에 없습니다.
D2Coding 등의 글꼴을 사용해 주세요.

**Comment by kms0219kms** [comment]
자세한건 #44 에서 확인해 주세요.

**Comment by orioncactus** [comment]
안녕하세요! 다른 비슷한 가변폭 글꼴에서도 제보해주신 것과 비슷하게 문제가 생기는지 확인해보고 알려드리겠습니다.

**Comment by kms0219kms** [comment]
Windows Terminal 외 VS Code, Atom 등 IDE에서도 동일한 문제가 발생합니다만,
D2Coding같은 mono-spaced 폰트는 해당 이슈가 발생하지 않습니다.

Noto Sans CJK KR 같은 경우 일부 글자만 해당 이슈가 발생하며,
나눔 고딕의 경우 모든 글자에 해당 이슈가 발생합니다.

**Comment by orioncactus** [comment]
오! 이렇게 대신 확인해주셔서 감사합니다! 일단 저도 주말에 해당 환경에서 어느 글꼴들에 동일한 문제가 발생하는지 확인해보려고 합니다.

**Comment by orioncactus** [comment]
확인해보았습니다. Monospace가 아닌 다른 글꼴에서 동일하게 발생하는 것을 보아, kms0219kms님께서 말씀해주신 것처럼 해당 현상은 글꼴 문제라기보다는 Pretendard가 고정폭 글꼴이 아니기 때문에 발생하는 현상으로 보입니다. 고정폭 Pretendard 개발은 아직 예정에 없기 때문에 이 이슈는 닫아두겠습니다. 추가적으로 도움이 필요한 부분이 있으시면 언제든지 알려주세요!
