### ISSUE TITLE
pretendard JP 폰트 웹 소스에 삽입하여 사용 시 사용불가

### ISSUE THREAD

**Issue by qkrdkwl9090** [orioncactus/pretendard#75]
pretendard-Bold.woff 등 폰트를 사용하다, 홈페이지에 있는 일본어 버전 폰트 다운받아  pretendardJP-Bold.woff로 폰트 변경하였는데,
대체 폰트로 대체됩니다. woff2로 수정 후, 적용해도 똑같네요.

woff파일을 다운받아 소스에 직접 넣는것 말고 추가로 해야하는것이 있을까요?

font-family: 'Pretendard JP', Meiryo ...

font-face {
		font-family: 'Pretendard JP';
		font-weight: 700;
		src: (생략)/static/fonts/PretendardJP-Bold.woff')}') format('woff');
}

**Comment by orioncactus** [comment]
다이나믹 서브셋을 제외한 모든 Pretendard JP 웹폰트를 Chrome에서 정상적으로 표시되지 않아, 다시 열었습니다. 확인해보고 다시 알려드리겠습니다. 그동안 Pretendard JP를 웹폰트로 사용하시려면 다이나믹 서브셋을 사용하시는 것을 추천드립니다.

#### HTML
```html
<link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard-jp-dynamic-subset.css" />
```

#### CSS
```css
@import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard-jp-dynamic-subset.css');
```

**Comment by orioncactus** [comment]
기다려주셔서 감사합니다. 정리한 내용은 다음과 같으며, 곧 문제를 수정한 1.3.1 버전을 배포할 예정입니다.

## 문제
- WebKit 엔진을 사용하지 않는 모든 브라우저에서 Pretendard JP를 사용할 때 일반 웹폰트 파일로는 전부 표시되지 않으며, 다이나믹 서브셋에서는 일부 subset 파일만 로드되지 않은 것을 확인
- 특정 글리프에서 생기는 문제임을 추측하고, FontTools에서 Glyph ID를 통한 subset 웹폰트 추출 방법으로 문제가 생기는 Glyph ID 점검
- 소스 파일에서 문제가 발생하는 글리프를 확인해보니, 다른 글리프와 unicode를 중복해서 사용하고 있었음
- 따라서, WebKit 엔진을 사용하지 않는 모든 브라우저에서 동일한 unicode를 공유하고 있는 글리프가 2개 이상일 때 글꼴이 로드되지 않는 것으로 보임

## 해결
- 동일한 unicode를 사용하고 있고, 중복된 uni585A.uv001 글리프와 uniFA10 글리프 중에서 uniFA10을 제거

## 확인 환경
- macOS 12.4, arm64
  - Chrome, 101.0.4951.64 
  - Safari, 15.5(17613.2.7.1.8)
  - Microsoft Edge, 101.0.1210.53
  - Firefox, 100.0.2
- Windows 10 Home 21H1, 64bit
  - Chrome, 101.0.4951.67
  - Microsoft Edge, 101.0.1210.53

**Comment by orioncactus** [comment]
이제 정상적으로 표시됩니다. 개선할 수 있게 이슈를 남겨주셔서 진심으로 감사드립니다!

**Comment by qkrdkwl9090** [comment]
정상 적용되는거 확인했습니다 .빠른 처리 감사합니다!
