### ISSUE TITLE
Flutter에서 pretendard 사용

### ISSUE THREAD

**Issue by broccolism** [orioncactus/pretendard#8]
안녕하세요!
플러터 프로젝트에 이 글꼴을 사용하고 싶은데, 폰트 적용이 제대로 되지 않아 이슈 올립니다.
.ttf, .otf 모두 해봤고 다른 웹폰트 등록하는 방식과 똑같이 했는데 다른 폰트만 제대로 뜨고 pretendard만 적용이 안되는 것 같습니다.
한번 확인해주실 수 있나요?
플러터는 2.2.3 버전을 사용하고 있습니다.

**Comment by broccolism** [comment]
보니까 플러터랑 연동될 때 뭔가 불안정해서 그런 것 같습니다. 적용이 되었다 안 되었다 하네요ㅠ
폰트 잘 쓰겠습니다 감사합니다!

**Comment by leejh10003** [comment]
@broccolism 혹시 #9 와 같이 설정했는지 확인 부탁드려요! 현재 플러터 2.2.2 기준으로는 정상 작동하는 것으로 확인했습니다!

**Comment by orioncactus** [comment]
@leejh10003 이렇게 Flutter 환경에서 Pretendard 지원을 확인해주시고 문서를 작성해주셔서 정말 감사드립니다!

추가적으로 개발 환경에서 더욱 쉽게 사용할 수 있도록 패키지로 제공하는 방법을 검토하고 있습니다. 더 나은 환경에서 Pretendard를 쓸 수 있도록 지속적으로 가꾸겠습니다. 감사합니다.

**Comment by broccolism** [comment]
@leejh10003 네 동일하게 설정했는데 처음에 .ttf 하나만 쓰거나 .otf를 쓰고 weight 지정을 안 해줘서 그랬던거같아요 .정확히 이거 때문인지는 모르겠지만, 지금은 잘 작동합니다! 감사합니다 ㅎㅎ
