### ISSUE TITLE
figma 사용 시 Strikethrough 위치 오류

### ISSUE THREAD

**Issue by yoongchoi** [orioncactus/pretendard#81]
<img width="250" alt="스크린샷 2022-06-07 오후 12 46 52" src="https://user-images.githubusercontent.com/107018547/172291666-3456a610-bca9-4710-98fd-7b651aa38a56.png">

figma에서 프리텐다드를 사용 중인데, 원래 중간을 통과해야하는 선이 자꾸 상단에 위치되어 있어 사용에 어려움을 겪고 있습니다.
최신 버전 설치했을 때 해당 이슈가 있어 예전 버전 중 하나를 설치해 정상적으로 사용하고 있었는데, 최근들어 다시 이런 이슈가 발생하고 있어 문의 드립니다.
혹시 해결할 수 있는 방법이 있을까요?

**Comment by orioncactus** [comment]
안녕하세요! 문제를 확인해보았으나, 최신 버전인 v1.3.3(1.301)에서는 말씀하신 현상을 찾지 못했습니다. 서체 관리자에서 Pretendard 버전이 1.301으로 표시되고 있는지 확인해보시고, 사용하고 계신 Figma 요금제가 Organization이라면, Admin settings/Resources/Shared fonts에서 Pretendard 버전이 1.301로 표시되고 있는지 확인해보시고 알려주시면 감사하겠습니다.

테스트 환경은 다음과 같습니다:
- macOS 12.4, arm64 | Figma 114.6.1

**Comment by yoongchoi** [comment]
혹시 os버전도 해당 에러에 영향을 끼치는 것일까요?ㅠㅠ
오래된 컴퓨터라 업데이트를 미루고 있는데(현재 bigsur 11.2), 우선 서체 삭제 후 재설치 - 피그마 114.6.1 업데이트 했을 때도 동일현상이 보여져서 여쭙습니다.

**Comment by yoongchoi** [comment]
혹시 os버전도 해당 에러에 영향을 끼치는 것일까요?ㅠㅠ
오래된 컴퓨터라 업데이트를 미루고 있는데(현재 bigsur 11.2), 우선 서체 삭제 후 재설치 - 피그마 114.6.1 업데이트 했을 때도 동일현상이 보여져서 여쭙습니다
<img width="265" alt="스크린샷 2022-06-08 오전 9 51 05" src="https://user-images.githubusercontent.com/107018547/172508175-85c4c36c-2639-4ed8-af19-50382adca158.png">

+ 서체관리자에서 폰트 삭제 이후에도 피그마에서 구버전 폰트가 보여지는 것 같습니다, 혹시 이 부분에 대해서도 해결 방안을 아실지하여 글 적어봅니다...🥲

**Comment by orioncactus** [comment]
Figma 플랜이 Organization인지 확인해보셨나요? Organization이 맞다면, 위에 말씀드린 방법대로 shared fonts에서 글꼴을 새로 업로드해 최신 버전으로 업데이트하실 수 있습니다. Figma에서 표시되는 Pretendard가 구버전인지 확인하려면 `~` 모양이 아래와 같은지 확인하시면 됩니다.

<img width="400" alt="tilde" src="https://user-images.githubusercontent.com/7247848/172510985-8491f51a-4f7d-468d-9c86-be7286bae306.png">

**Comment by yoongchoi** [comment]
답변 감사드립니다, 요금제는 organization이나,프리텐다드를 팀 공통으로 공유/사용한 것이 아닌 개인이 로컬 폰트로 다운/설치하여 사용 중이었어서인지 shared font 창에서는 표시가 되지 않고 있습니다!(서체관리자에서 삭제를 했는데, 피그마에선 보여지고 있는 이슈) 
우선 현재 물결기호는 해당과 같이 표시되고 있습니다(strike through 적용 중)
<img width="619" alt="스크린샷 2022-06-08 오전 11 13 39" src="https://user-images.githubusercontent.com/107018547/172516528-27c6c085-c4d8-43e3-b00e-389bee6d80e7.png">

**Comment by orioncactus** [comment]
보내주신 것을 보니 최신 버전에서 표시되는 tilde 모양과 달라 이전 버전인 1.1(1.100)이 맞아 보입니다. 서체 관리자에서 모든 서체에 Pretendard가 없는 것이 맞다면, 팀 계정이 아닌 개인 계정으로 Figma를 사용해보신 다음에, 개인 계정에서도 Pretendard가 표시되는지 확인해보시겠어요? 만약 개인 계정에서도 Pretendard가 표시된다면 Adobe Fonts나 산돌구름에서 Pretendard가 활성화된 상태일 수 있으며, 표시되지 않는다면 팀에서 shared fonts로 사용하고 있는 것일 수 있습니다.

**Comment by yoongchoi** [comment]
네 감사합니다. 말씀해주신 대로 외부폰트에서 활성화 되고 있었습니다. 도움 주신 덕에 개운하게 해결 되었습니다! 감사합니다 :)

**Comment by orioncactus** [comment]
해결되어 다행입니다. 저도 외부 글꼴 관리자에서 제공하는 Pretendard 버전을 확인해보고, 최신 버전으로 업데이트될 수 있도록 확인해보겠습니다. 이 이슈는 이제 종결로 처리하겠습니다! :D
