### ISSUE TITLE
특수문자에 비해 글자가 위로 밀려있는 문제 .. 

### ISSUE THREAD

**Issue by n0ch4t** [orioncactus/pretendard#84]
- chrome
<img width="600" alt="Screenshot 2022-07-06 at 10 37 31" src="https://user-images.githubusercontent.com/47148451/177448772-6d7aea32-4d01-4608-b832-ced8fddc76ea.png">

- mobile ios safari
![ipadsafari](https://user-images.githubusercontent.com/47148451/177452544-85f6e3cb-67a0-4f68-bafe-6fc86f34ebfd.png)

안녕하세요.
최신버전 폰트를 적용하여 테스트를 해보고 있는데요.
'(' 나 '/' 등의 특수문자들에 비해 글자가 위로 밀려있어 아래쪽 여백이 상대적으로 많이 남아
정렬 시에 어색해보이는 경우가 존재 하게되는데
이런 부분도 개선이 가능 할까요 ?

version: v1.3.4

**Comment by orioncactus** [comment]
확인해주셔서 감사드립니다!

확인해보니 이번 모노레포 업데이트로 `pretendard` 및 `pretendard-subset` 웹폰트 에셋에서 OpenType 기능이 제외된 상태로 배포되었네요. 당분간은 `pretendard-dynamic-subset`를 사용하시는 것을 추천드립니다 😅 말씀하신 문제는 조만간 빠르게 수정해 배포될 때 다시 알려드리겠습니다!

**Comment by n0ch4t** [comment]
@orioncactus 캄사합니다!

**Comment by orioncactus** [comment]
@Gamsake님의 도움으로 문제를 수정한 새 버전을 배포했습니다. 이제 일반 Pretendard 웹폰트에서도 OpenType 기능을 자유롭게 쓰실 수 있습니다 ლ(´ڡ`ლ)
