### ISSUE TITLE
v1.3.4에서 다이나믹 서브셋을 제외한 웹폰트 에셋에 OpenType 기능이 제외됨

### ISSUE THREAD

**Issue by orioncactus** [orioncactus/pretendard#85]
#84 에서 제보됨

# 개요
- 웹폰트에서 dynamic-subset이 아닌 다른 모든 에셋(static, subset, variable)에 pyftsubset option이 적용되지 않음

**Comment by black7375** [comment]
서브셋 시 옵션 때문일 수도 있습니다.
다만 대부분의 옵션은 비슷하게 쓰여서 조사가 필요할 듯 합니다.

- 일반 서브셋에서 쓰이는 옵션
https://github.com/orioncactus/pretendard/blob/2e210b5a4d0b3f10f33cc363df9e4c96d6fe88cc/packages/subset-utils/src/normal-subset.ts#L17-L34
- 다이나믹 서브셋에서 쓰이는 옵션
https://github.com/black7375/font-range/blob/eeab711539c9b35ad5010c8466b265772800c3e4/src/main.ts#L143-L159

**Comment by orioncactus** [comment]
Subset 자동화에서 layout-option이 있는데도 제외된 게 이상하네요 🤔 일반 Pretendard 에셋에도 동일하게 문제가 있어서, 저도 어떤 문제인지 확인해보겠습니다!
