### ISSUE TITLE
가변 폰트의 웹폰트 다이나믹 서브셋 제공

### ISSUE THREAD

**Issue by hiddenest** [orioncactus/pretendard#90]
> **⚠️ Experimental**  
> 구현 및 실제 환경에 적용 가능한지 테스트를 하고 있습니다.  
> 해당 내용이 불가능하다고 판단될 경우 Issue를 닫을 수 있습니다.

## 개요
#4 의 연장선상에서 진행하는 작업입니다.
가변 폰트(Variable Font)도 다이나믹 서브셋을 적용하여 최신 웹 환경에서 더 적은 용량으로 폰트를 불러와 사용할 수 있도록 합니다.

## 구현 방식
Google의 경우, weight를 선택하면 주소 파라미터에 `@wght` 값이 붙으며, 입력한 값 각각에 대해 `font-weight` 의 CSS가 생성됩니다.
이때 불러오는 파일의 경로는 모두 동일합니다. 구현 방법을 차용하여 구현할 수 있는지를 실험해보려고 합니다.
- `subset-utils` 에서 kinds가 `"dynamic"`일 때, `variable` 여부를 받을 수 있도록 합니다.
- `variable` 여부에 따라 INPUT_PATH, DIST_PATH, CSS 파일명을 수정합니다.
- 각 폰트 패키지 내의 `dist/web/variable` 내에 템플릿 CSS를 추가합니다.

**Comment by orioncactus** [comment]
@hiddenest님 안녕하세요! 모던 브라우저에서 웹폰트 용량 최적화를 위한 방법을 고민해주셔서 정말 감사드립니다! 이어 올려주신 PR을 확인하고 PR에서 댓글로 계속하겠습니다 🚀
