### ISSUE TITLE
한글(HWP)와 리브레오피스에서 Bold가 나타나지 않음

### ISSUE THREAD

**Issue by black7375** [orioncactus/pretendard#93]
**환경**
- Windows 10
- HWP 2022
- Pretendard v1.3.5 public의 ttf를 설치

`C:\Windows\Fonts\Pretendard`에 정상적으로 설치되었습니다.
![image](https://user-images.githubusercontent.com/25581533/190391714-1249ce29-fa95-4e1f-a852-9d35e9d58c6c.png)

**문제**
그런데 한글과 리브레오피스에서 볼드체만 보이지 않습니다.
![image](https://user-images.githubusercontent.com/25581533/190391796-2aaf204f-684f-4e03-85b1-5772f718589a.png)
![image](https://user-images.githubusercontent.com/25581533/190397215-2f16b7c0-ce88-4eef-a2e2-4fef8f2971ee.png)

Office 365는 아직 설치하지 않아서 어떠한지 모르겠네요.

**Comment by orioncactus** [comment]
안녕하세요!

Pretendard Regular와 Pretendard Bold는 Style linking이라고 해서 서로 같은 패밀리로 바라보게 해두었습니다. 따라서 Pretendard Bold가 보이지 않는다면, 일반 Pretendard를 선택하시고 애플리케이션에서 지원하는 Bold 기능을 통해 Pretendard Bold를 활성화할 수 있습니다.

Microsoft Office 및 LibreOffice, 한컴오피스에서는 ‘굵은 가’ 아이콘을 선택하시면 적용되는 것으로 알고 있는데요, 한번 해당 아이콘을 눌러 활성화해보시겠어요?

**Comment by black7375** [comment]
헉 그런 기능도 있었군요
예전에 산돌이나 릭스에서 제공하던 폰트를 사용할때는 볼드체가 따로보이길래 원래 따로나오는건줄 알았어요.

친절한 답변 감사합니다.

**Comment by AlexSeanYoon** [comment]
유사한 질문이 있었군요~ㅎㅎ
나름 히스토리를 보고 없길래 올렸는데...제가 놓쳤었나 봅니다.
감사해요^^ @black7375

**Comment by black7375** [comment]
@AlexSeanYoon 어... 지금보니 제 스크린샷에는 9개 폰트가 보이네요?
방금 여셨던 이슈는 관리자님께서 답변해주시는게 가장 정확할 듯 합니다.
