### ISSUE TITLE
Pretendard Variable 다이나믹 서브셋에 대한 리드미 내용이 없습니다.

### ISSUE THREAD

**Issue by kms0219kms** [orioncactus/pretendard#94]
Pretendard Variable 다이나믹 서브셋에 대한 리드미 내용이 없습니다.

아마 누락된거 같은데, 추가 해 주실 수 있으실까요?

**Comment by kms0219kms** [comment]
시간 될 때 PR로 넘겨드리겠습니다.

**Comment by orioncactus** [comment]
안녕하세요! Pretendard Variable 다이나믹 서브셋은 월요일 오전에 새 릴리즈로 맞춰 배포할 예정입니다. 문서화도 릴리즈 전에 마무리할 예정이라서, 제가 월요일 오전에 배포한 이후에 이 이슈는 종결하도록 하겠습니다!

**Comment by kms0219kms** [comment]
아 넵 알겠습니다!

**Comment by orioncactus** [comment]
제가 요즘 바빠 손을 대지 못하고 있는데요, 다음주 월요일 전까지는 마무리해서 올려두겠습니다!

**Comment by kms0219kms** [comment]
PR 드렸습니다. 확인 후 머지해 주세요.

**Comment by orioncactus** [comment]
제가 진행 상황을 미리 공유드리지 못해 죄송합니다 🥲 기여해주신 #100 은 이전에 작업하고 있던 #102 으로 대신해 적용했습니다. 이 이슈는 종결로 처리하고, 다음에는 진행 상황을 미리 알려드리겠습니다! 🙇
